USAGE.md

Just in case the user does not have `pip` or `python3.11-venv`.
This allows generating a valid prompt now.
Will test more after creating a test gcloud to use VertexAI.

Add more dependencies

---

data_prep/project_context/context_retriever.py
run_one_experiment.py

Add uuid to AST directory generation to prevent race condition when multiple experiments are run with the same project, causing a potential race when one experiment is downloading and copying the ast files to the project ast directory and when the other experiment is iterating over the files within that ast directory.
Fixes #20

Add uuid to ast dir generation in context retrieval to prevent race condition

---

.github/workflows/push-to-gcloud.yml

The docker build tag wasn't updated to the new artifact registry URL

Fix Github action to push to gcloud

---

.github/workflows/push-pr-to-gcloud.yml
.github/workflows/push-to-gcloud.yml

Github action to build a gcloud docker image for PR requests

---

report/docker_run.sh

As we start to have many reports (from daily, one-off, pr), I wanted to use sub-directory as an easy way to visually categorize reports to keep the directory more organized.
@erfanio also proposed using tags in the report, which will provide more dimensionality in classification later.

Use sub-directories to categorize reports

---

.github/workflows/lint.yaml
.github/workflows/push-pr-to-gcloud.yml

The current setting does not lint PRs like https://github.com/google/oss-fuzz-gen/pull/82 and https://github.com/google/oss-fuzz-gen/pull/81, nor build images for them for testing purposes.
This PR fixes that.

Enable linting and building images for all PRs

---

data_prep/introspector.py

Seeing this error occurred on some projects when generating benchmarks.
Log the project name for this error in case this happens again so that we can re-generate the benchmark.yaml for that project.

Catch the error in preparing OSS-Fuzz for benchmark generation.

---

experiment/oss_fuzz_checkout.py

Hiding the error message details because:
1. The error is expected in all local experiments: OSS-Fuzz dir (`/tmp/<tmp_dir>/build/work`) contains the files copied from the docker container, which requires root privilege to delete.
2. The error is benign: Temp dir is in `/tmp` and will be automatically deleted by OS.
3. The error is hard to fix: Fixing this requires using `sudo` or docker, which adds too much unnecessary effort.
We did not have this problem before because we used `pass`:
https://github.com/google/oss-fuzz-gen/commit/9885ae16b9f12686b504eecd94b35641f27c608a#diff-c265089165acff162907dbef5c22b1f966e638b1e750bee28c5a548262464fc3L40
Now, we also log a warning in case this happens elsewhere.

Hide the error message when deleting temp OSS-Fuzz dir

---

report/docker_run.sh
report/templates/index.html
report/templates/index.json
report/upload_report.sh
report/web.py

The current report displays function by its `raw_function_name`, which is not human-readable.
This PR replaces that with the corresponding function signature found in the benchmark set used in the experiment.
Related: https://github.com/google/oss-fuzz-gen/pull/98#issuecomment-1938208683

Use function signature in report

---

data_prep/project_targets.py

[Recent experiment result](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-02-14-106-dg-comparison/benchmark/output-avahi-avahi_dns_packet_new_reply) shows a regression in prompt generation:
`project_targets.py` failed to find the correct function signature for human-written targets.
This PR fixes this by using the latest function signature API from FuzzIntrospector.
To avoid code conflicts, it adds the function to `project_targets.py`.
@cjx10: Could you please move the two new functions to `introspection.py` before/after your change?
Thanks!

Fix function signature in `project_targets.py`

---

experiment/evaluator.py

Docker appears to have an undocumented name rule that disallows dashes (`-`) followed by underscores (`_`) (and `-`s after `_`), which caused some of our projects to fail to build.
This PR fixes this issue by replacing these patterns (`[_-]{2, }`) with `-`.

Replace `-_` or `_-` patterns with `-`

---

.github/helper/presubmit

1. Apply `pylint` on each file explicitly. Some errors were not captured in #112, this should fix it.
2. Only check committed files. Unstaged files will not be pushed anyway, and leaving them can make local tests more flexible.
3. Use a more specific path to dot files to avoid any ambiguity.
4. Disable a false warning from `shellcheck`, because it cannot interpret path correctly.

Fix and improve CI lint

---

llm_toolkit/code_fixer.py
llm_toolkit/models.py
llm_toolkit/prompt_builder.py
llm_toolkit/prompts.py
run_all_experiments.py
run_one_experiment.py

The logic was getting a bit too entangled and difficult to extend.
This breaks out the prompt generation into its a separate prompt_builder module, as well as introduces Prompt classes (with both TextPrompt and OpenAIPrompt as two implementations).
This also changes the model interfaces to take in a Prompt object instead of `prompt_path`. `prompt_path` was only really needed for logging and AIBinaryModel.
Ref: #62.

Refactor: Separate out prompt generation from model.

---

report/docker_run.sh
report/templates/base.html
report/upload_report.sh
report/web.py

Support specifying models in GKE experiment runs
1. Add `model` argument to `docker_run.sh`, `upload_report.sh`, and `web.py`.
2. Display the model name in experiment reports
3. Some TODOs to rewrite code to adapt to increasing complexity.
Preview:
We can beautify the layout later.

Support specifying models in GKE experiment runs

---

.github/workflows/push-weekly-image-to-gcloud.yml

1. Add workflow to build a docker image with the latest code in `main`
2. Push the image to the artifact registry on Saturday at 1 AM.
I will also run some experiments here for testing purposes.

Push image for weekly experiments

---

report/web.py

The current report only shows the name of LLM used on `index` and `sort` pages.
This PR will show them on all pages.

Show LLM name on all report pages

---

report/docker_run.sh
run_all_experiments.py

Current large-scale experiments tend to exceed various quota limits (e.g., cloud build).
This PR delays each benchmark's experiment by N seconds to amortize the quota usage, at the cost of starting some experiments relatively later than others.
For example, a 10-second delay will launch the last benchmark experiment 4+ hours later than the first.
This is acceptable because it is only used for large-scale experiments, which tend to have hours of fuzzing timeout.
This is a temporary solution. Ideally, we want a universal controller for safer and more efficient usage control.

Allow delaying each experiment

---

report/web.py

Current `web.py` spams logging because it prints out the target path every time we get the target.
This PR fixes that by only log them for dubeg.
This makes the log from large experiments (e.g., `all`) more human-friendly.

Avoid spamming the logs with result path

---

experiment/builder_runner.py
report/aggregate_coverage_diff.py

The code excludes line coverage of fuzz target, which duplicates #135.

Remove duplicate code in coverage measurement

---

experiment/textcov.py

We count the #unique line coverage of the new fuzz targets by subtracting the lines covered by existing targets.
However, the current code does not exclude unhit lines in existing targets.
This PR fixes that by only subtracting lines with a non-zero hit count.
This PR also:
1. Adds a new helper function to assisting debug this or similar issues in the future.
2. Fixes a minor typo in function pattern when matching `covreport`, which misses the first char in function name.

Fix unique line coverage counting

---

.gitignore

Avoid considering files that are open in vim.

gitignore: avoid .swp files

---

llm_toolkit/models.py
run_one_experiment.py

This is to avoid confusing output about Vertex AI when using models other than Vertex AI. 
For example, currently when I run e.g. using `openai` model I get output about Vertex AI location:
```sh
$ ./run_all_experiments.py --model=gpt-3.5-turbo --benchmarks-directory=./benchmark-sets/comparison-2/
Running 2 experiment(s) in parallel.                                                                                                                                                                                    
INFO:root:Using location us-central1 for vertex AI                                                                                                                                                                      
Downloaded human-written fuzz targets of tinyxml2 from Google …
```

models: make cloud_setup class-specific

---

data_prep/parse_training_data.py

The current script assumes the result directory is available locally, which does not support old cloud experiment results.
The code change downloads necessary files from old experiment bucket directories and uses them to generate training data.
Note: Future experiments will automatically generate training data, thanks to #148. This is only used to generate training data from past experiments.

Allow generating training data with old experiment results.

---

data_prep/README.md

The original example has been removed and its link is invalid, and an existing case [`capnproto.yaml`](../benchmark-sets/all/capnproto.yaml#L44) is now updated.

Update README.md by fixing an invalid link instance.

---

data_prep/README.md
data_prep/introspector.py

--> This builds on top of https://github.com/google/oss-fuzz-gen/pull/141 so will rebase once that has landed.
Adds ability to use a local deployment of Fuzz Introspector's web api instead of using https://introspector.oss-fuzz.com/
This has several benefits. Deploying a local version and pointing oss-fuzz-gen to this will:
- For larger experiments avoid any timeout issues incurred by too many requests to `introspector.oss-fuzz.com`. Local will have no issues responding to requests.
- Testing new things will go faster as it's not necessary to deploy a new version of the API by way of  `introspector.oss-fuzz.com` before oss-fuzz-gen can use it.
- If for some reason some limitations or regressions are landed on `introspector.oss-fuzz.com` then oss-fuzz-gen testing against introspector isn't …

Make it possible to point to a local deployment of Fuzz Introspector

---

data_prep/introspector.py

Set the default endpoint on import.
Our experiment runs (from run_one_experiment) wasn't setting this.

Fix introspector endpoint in experiments.

---

experiment/evaluator.py

three types of cases are handled:
- driver that has no coverage increase
- false positives by crashing at INITED or first few rounds
- false positives by crashing at `LLVMFuzzerTestOneInput`

detect and filter incorrect fuzz drivers

---

report/templates/sample.html
report/web.py

Fixes incorrect usage of `sample`:
It was a string on that page, now changing it to the `Sample` Object so that we can show its results and crash reason on the page.
Preview:

Fix report sample page

---

report/upload_report.sh
report/web.py

This PR fixes the benchmark page link in sorted index pages, e.g.:
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-03-21-172-dg-comparison/sort/crash
Related: https://github.com/google/oss-fuzz-gen/pull/172/commits/baf80ff4367ca77b1b2b7403bbb535802cc0eb6c

Modify sort keys in web.py

---

report/templates/base.html
report/templates/benchmark.html
report/templates/index.html
report/templates/sample.html
report/web.py

* The tables are much prettier
* The index.html table has sortable columns
* The index.html table has an index column
* Fix a bug in the signature matching algorithm where it returned early on prefix matches.
* Prevent the licence to show up in the HTML (often multiple times).
Preview:

Improve the usability of the experiment reports

---

experiment/evaluator.py

Without this trying to generate a report for an old experiment crashes web.py

Make renamed `is_semantic_error` field backward compatible

---

experiment/evaluator.py

The old code incorrectly treats a failure in fixing semantic errors as a failure in fixing build error, hence it incorrectly labels buildable but semantically wrong fuzz targets as not buildable.
PoE: https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-04-11-daily-comparison/benchmark/output-fribidi-fribidi_log2vis/index.html
This PR fixes it.

Fix incorrect build result with build success + semantic error

---

experiment/builder_runner.py
experiment/evaluator.py

This is an initial attempt to move semantic result into run result (mentioned in [PR 204 comments](https://github.com/google/oss-fuzz-gen/pull/204#discussion_r1555217940)):
- the run and fix loop in `do_check_target` function is simplified
- log parsing logic (originally in `do_check_target`) is moved into the `BuilderRunner` class
- now `SemanticCheckResult` is a member of `RunResult`
Please told me if there is any further improvement idea for the refactor!

Move semantic result to run result

---

report/templates/benchmark.html
report/templates/crash.json
report/upload_report.sh
report/web.py

Current reports fail to generate `crash.json` page because `benchmark_json()` misuses its parameter `benchmark` (a `str`) as a `Benchmark` class.
This PR fixes it by adding a new function to generate `Benchmark()` with the `benchmark` string.
The PR also adds the missing index JSON, and removes outdated sorting pages.

Fix crash.json page in report.

---

report/templates/benchmark.html

In the benchmark page:
1. Use green if the value in the `Builds` column is `True`.
2. Use red if the value in the `Crashes` or `Bug` columns is `False`.

Color results in reports for better readability

---

experiment/builder_runner.py
experiment/fuzz_target_error.py

Consider `null-deref` as a semantic error instead of a bug:
1. It is likely due to inadequate parameter initialization or incorrect library usage in the fuzz target 
2. It is hardly exploitable.

Capturing `null-deref` as a semantic error 

---

benchmark-sets/all/readstat.yaml

The previous one wasn't built: https://github.com/google/oss-fuzz/blob/bf577d8664b7f7c06ba42f95c01f9161c73cd5ff/projects/readstat/build.sh#L38

Fix target name and path for readstat

---

.gitignore
data_prep/introspector.py
report/docker_run.sh
run_all_experiments.py

This makes it possible to run experiments without having to generate benchmarks prior, and also makes it possible select one or more benchmarks to generate for X amount of projects.
Example run:
```sh
./run_all_experiments.py \
--model=gpt-3.5-turbo -g low-cov-with-fuzz-keyword,far-reach-low-coverage -p htslib -m 6
```
Run for multiple projects:
```sh
./run_all_experiments.py \
--model=gpt-3.5-turbo -g low-cov-with-fuzz-keyword,far-reach-low-coverage -p htslib,tinyxml2 -m 6
```

Make it possible to create benchmarks during experimentation

---

experimental/c-cpp/build_generator.py
experimental/c-cpp/runner.py

Add another build heuristic that deals with project that declare a specific compiler in their `Makefile`. For example, some projects will set
`CC = gcc` and in these cases we need to adjust such that the Makefile doesn't hardcode the compiler but rather uses the one supplied by OSS-Fuzz

experimental: add another build heuristic

---

experimental/c-cpp/manager.py
experimental/c-cpp/runner.py

This adds output from the build/evaluator to create clean OSS-Fuzz/CFLite projects for each successful harness generated. These can be copied over to OSS-Fuzz and run without issues.

experimental: output clean OSS-Fuzz & CFLite folders

---

.github/dependabot.yml

Noticed a few actions used in the workflows here are outdated, proposing a Dependabot configuration to update - reference https://docs.github.com/en/actions/security-guides/using-githubs-security-features-to-secure-your-use-of-github-actions#keeping-the-actions-in-your-workflows-secure-and-up-to-date
Resolves warnings in executions ex. https://github.com/google/oss-fuzz-gen/actions/runs/7837148809
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4
Suggest enabling https://docs.github.com/en/code-security/dependabot/working-with-dependabot/about-dependabot-on-github-actions-runners#enabling-or-disabling-for-your-repository as well.

Dependabot configuration to update actions in workflows

---

llm_toolkit/code_fixer.py
llm_toolkit/output_parser.py
prompts/template_xml/fixer_priming.txt

Passing the raw response can confuse LLM when it contains more text than the code block, which occurred on `Gemini 1.5`.
Also, `Gemini 1.5`'s response structure seems to be different from `code-bison-32k`.
This PR does two things:
1. Make the response parser compatible with both models.
2. Pass the code block in response to LLM fixer, not the raw response.

Pass code block to fixer prompt, not the raw LLM response

---

llm_toolkit/code_fixer.py
llm_toolkit/output_parser.py
prompts/template_xml/fixer_priming.txt

Passing the raw response can confuse LLM when it contains more text than the code block, which occurred on `Gemini 1.5`.
Also, `Gemini 1.5`'s response structure seems to be different from `code-bison-32k`.
This PR does three things:
1. Make the response parser compatible with both models.
2. Pass the code block in response to LLM fixer, not the raw response.
3. More instructions in the code-fixing prompt to avoid common mistakes.

Pass code block to fixer prompt, not the raw LLM response (#259)

---

experimental/c-cpp/build_generator.py

Sometimes projects will have default options on that can cause build issues, and being able to switch these off enable builds to succeed. This cmake option adds the ability to run a CMake run listing all options available, and enables turning off those default values that are ON.

experimental: add extended cmake options build heuristic

---

experimental/c-cpp/runner.py

This is needed when doing large-scale experiments.

experimental: clean up used containers

---

experiment/evaluator.py
llm_toolkit/models.py
run_one_experiment.py

This PR captures the following error from Vertex AI model:
```python
ERROR 2024-05-08T14:54:27.598104660Z File "/venv/lib/python3.11/site-packages/vertexai/generative_models/_generative_models.py", line 1653, in _append_gapic_content
ERROR 2024-05-08T14:54:27.598107350Z raise ValueError(
ERROR 2024-05-08T14:54:27.598117270Z ValueError: Content roles do not match: model !=
```
Background:
Some benchmarks from our full experiment break when querying LLM, causing [non-terminating experiments](https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-05-08-weekly-all/benchmark/output-apache-httpd-register_hooks/index.html).
For example, here we have the prompt but not the response:
https://pantheon.corp.google.com/storage/browser/oss-fuzz-gcb-experiment-run-logs/Result-reports/scheduled/2024- …

Capture multiple errors in LLM query

---

experiment/builder_runner.py
experiment/evaluator.py
llm_toolkit/models.py

This PR fixes a `libfuzzer` parser error and captures other errors when building and running fuzz targets.
Related:
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-05-15-273-dg-273-comparison/benchmark/output-libusb-libusb_get_string_descriptor_ascii/index.html
https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22oss-fuzz%22%0Aresource.labels.location%3D%22us-central1-c%22%0Aresource.labels.cluster_name%3D%22llm-experiment%22%0Aresource.labels.namespace_name%3D%22default%22%0Alabels.k8s-pod%2Fbatch_kubernetes_io%2Fcontroller-uid%3D%22cb8a5fcb-948d-4faf-b1b7-bd16baee7f83%22%20severity%3E%3DDEFAULT%0A;cursorTimestamp=2024-05-15T07:34:10.709184162Z;startTime=2024-05-15T07:14:00.000Z?e=-13802955&mods=logs_tg_prod&projec …

Capture errors when building and running fuzz targets

---

experiment/builder_runner.py

The previous pattern does not catch this:
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-05-16-276-dg-276-1-comparison/sample/output-libusb-libusb_get_string_descriptor_ascii/03

Match another oom pattern in crash log

---

report/web.py

This report did not include fuzz targets with `.c++`, causing [previous report](https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-05-18-weekly-all/benchmark/output-capnproto-_zn5capnp13dynamicstruct7builder5adopten2kj9stringptreons_6orphanins_12dynamicvalueeee/index.html) failed to show them.

Add missing extension `.c++` to report

---

experiment/oss_fuzz_checkout.py

This is useful when having a shared virtual environment with other projects. For example, on my local dev I use a virtualenv environment with both fuzz introspector and oss-fuzz-gen requirements, but this is currently being blocked by the logic here trying to launch a new venv.

oss-fuzz-checkout: enable using own venv

---

ci/Dockerfile

This is to make the output of the CI consistent with the environment in which experiments run. It's now set to match: https://github.com/google/oss-fuzz-gen/blob/68c69a0ef888003371a12cb65b2ba5e27bc1a767/Dockerfile#L41
Otherwise we run into inconsistencies where e.g. https://github.com/google/oss-fuzz-gen/pull/300 reports:
```sh
Step #1: PR: https://github.com/google/oss-fuzz-gen/pull/300
Step #1: JOB: https://console.cloud.google.com/kubernetes/job/us-central1-c/llm-experiment/default/ofg-pr-300-dk
Step #1: REPORT: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-05-28-300-dk-comparison/index.html
Step #1: BUCKET: https://console.cloud.google.com/storage/browser/oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-05-28-300-dk-comparison
Step #1: BUCKET GS: …
```

ci: adjust timezone

---

run_all_experiments.py

Otherwise we will use the default endpoint when we also generate benchmarks during the run (happens inside of `get_experiment_configs`). This commit ensures we use the right endpoint in both local and cloud-based runs.

run_all_experiments: set introspector endpoint as early as possible

---

data_prep/introspector.py

We have multiple oracles for finding target functions and some of these may return empty for some projects. For example, the following command:
```sh
./run_all_experiments.py \
--model=gpt-3.5-turbo \
-g low-cov-with-fuzz-keyword,far-reach-low-coverage \
-gp $PROJECT \
-gm 6 \
-e http://127.0.0.1:8080/api
```
returns 0 interesting functions for the `low-cov-with-fuzz-keyword` oracle. However, the next oracle returns a list of candidates, so we should not exit upon the first oracle returning an empty list of candidate functions.
This allows oracles to return empty list of functions without exiting.

introspector: allow oracles to return empty lists

---

experiment/evaluator.py
experiment/textcov.py

This PR fixes line calculation for JVM projects in textcov analysis. It also filter out fuzzer classes from the coverage analysis to decrease noise.

Fix text coverage analysis for jvm projects

---

data_prep/introspector.py

As some of the arguments may have the exact same object types, the current name generation for method arguments could result in using the same name for multiple arguments of the same method. This PR proposes a fix to generate argument names according to its position to avoid duplication.

[JVM] Fix argument name bug

---

llm_toolkit/prompt_builder.py
prompts/template_xml/jvm_arg_description.txt
prompts/template_xml/jvm_generic_arg_description.txt
prompts/template_xml/jvm_problem_constructor.txt
prompts/template_xml/jvm_problem_method.txt
prompts/template_xml/jvm_specific_data_filler.txt
run_one_experiment.py

For Java projects, some of the methods may require arguments with generic types. This PR proposes a fix to include generic type suggestions in the prompts to allow the LLM generate a better result related to methods with generic type arguments.

[JVM] Add handling for generic argument types

---

experiment/evaluator.py

During development it's convenient to being able to adjust this, for example when focus during development is on aspects of OSS-Fuzz-gen that is unrelated to code fixing it's convenient to decrease this to speed up evaluation.

experiment: make LLM_FIX_LIMIT adjustable

---

data_prep/project_src.py

A more precise approach is needed when searching for potential harnesses due to performance issues.
For example, when analyzing `croaring` the following files all match the existing set up, but none of them have the potential of being the actual source code of a harness.
```sh
/tmp/tmpjg7oqx4m/out/src/croaring/build-dir/CMakeFiles/CMakeScratch/TryCompile-9ReWwb/cmake_install.cmake
/tmp/tmpjg7oqx4m/out/src/croaring/build-dir/CMakeFiles/CMakeScratch/TryCompile-9ReWwb/CMakeFiles/cmake.check_cache
/tmp/tmpjg7oqx4m/out/src/croaring/build-dir/CMakeFiles/CMakeScratch/TryCompile-9ReWwb/CMakeFiles/CMakeDirectoryInformation.cmake
/tmp/tmpjg7oqx4m/out/src/croaring/build-dir/CMakeFiles/CMakeScratch/TryCompile-9ReWwb/CMakeFiles/cmTC_bc5f1.dir/DependInfo.cmake …
```

data_prep: only include c/cpp files as potential harnesses

---

experiment/builder_runner.py

The prebuild check for JVM projects has missed the consideration of a method call across multiple lines, this cause some prebuild check failed to locate the target method call when it is split into multiple lines which result in false negative denial of possible valid fuzzing harnesses. This PR proposes a fix in the prebuild check to ensure multiple lines target method call could be recognised and fix the problem of false negative denial of possible valid fuzzing harnesses.

Fix bug in jvm prebuild check

---

data_prep/introspector.py

Introspector supports an additional API oracle for target querying. It would be nice to make this available for prompt development.

introspector: add another target oracle api

---

data_prep/project_src.py

Without doing this the containers are left hanging, which causes issues for local runs since the specific container is used multiple times in a single experiment.

project_src: stop containers that were started to collected src

---

data_prep/project_src.py

There is an issue when identifying harnesses for C projects. Currently, because of a missing language check all files in a C project will be considered valid C harnesses. Thus, when we identify the harnesss to subtitute our auto-gen code with we pick one from the "potential harness" list
https://github.com/google/oss-fuzz-gen/blob/0bed2b5a60d4af36bc0bc7565c57558bb08897da/data_prep/introspector.py#L422 
which effectively means that the majority of times (chance of `pick_one` choosing a valid harness is total harnesses divided by total C files (and many others prior to https://github.com/google/oss-fuzz-gen/pull/317)) a non-harness will be selected for substitution. Consequently, the auto-gen code will not be used.
This was causing a lot of weirdness with a C-specific prompt I'm building …

project_src: fix C harness identification

---

experiment/builder_runner.py

This pull request enhances the accuracy of function validation in the [_contains_target_function](https://github.com/google/oss-fuzz-gen/blob/8d8a8bd877ac4baf4a405c12b6ba1faf8fe35de1/experiment/builder_runner.py#L147) method. The original implementation used a simple substring check [min_func_name in generated_code](https://github.com/google/oss-fuzz-gen/blob/8d8a8bd877ac4baf4a405c12b6ba1faf8fe35de1/experiment/builder_runner.py#L155), which could lead to false positives when function names are similar but not identical, such as sf_open versus sf_open_fd.
For example:

Fix FN when matching func in driver

---

experiment/builder_runner.py

@arthurscchan `check_cov_increase` was added in https://github.com/google/oss-fuzz-gen/pull/236/files#diff-0b3fc09b0cd7a72a95a428b53477f27c2f85c45c483f7bf6a4c8666233b8a887R239 but never actually did anything?
Turned out to be a missing check when collecting coverage, which can cause false negatives. This PR fixes it.

runner: fix unused JVM coverage var

---

experiment/builder_runner.py

The logs are about building rather than running a given harness, which was a bit confusing when debugging. I assume because it was copied or so from here: https://github.com/google/oss-fuzz-gen/blob/bb7d3f80fb6feba4319b56e64f9603f3b0965999/experiment/builder_runner.py#L429-L432

runner: fix log message

---

data_prep/introspector.py

Introspector added a heuristic for avoiding static functions and we should use this by default when picking fuzz targets. This avoids hitting harnesses that will fail.
I made this default, but with an option as I assume it will more or less never be desired to have static functions as potential targets. However, there are cases where harnesses for static functions are interesting, although it would require either (1) removal of `static` by the harness construction logic or (2) adding the harness to the relevant file. For these reasons I keep it as an option, in case someone wants to give those types of harnesses a go.
Tested with:
```sh
./run_all_experiments.py \
--model=${MODEL}
-g far-reach-low-coverage,low-cov-with-fuzz-keyword,easy-params-far-reach \
-gp croaring \
-gm 15 \ …
```

introspector: avoid static functions for targets by default 

---

USAGE.md
report/upload_report.sh
report/web.py

Use argparse for the report generation and adjust USAGE.md accordingly. A benefit of this is that instructions will only be deprecated if we change argument names in the future.

report: use argparse to parse arguments

---

report/web.py

Using `gs://` paths the report generation tool directly read/write files directly from/to GCS.
The experiment nodes will continue using local file system. But now we have additional flexibility to regenerate reports without downloading the results which can be very big (hundreds of GBs for "all" benchmark set). This is a necessary first step for implementing trends report (go/oss-fuzz-gen-reports) which will require back-filling existing reports.
Testing it on a daily comparison result, it took ~11 minutes to generate. This is still pretty slow but we can optimize further later. For now this is good enough if we need to regenerate reports after an experiment is done.

Report generation tool supports GCS path for input/ouput paths

---

experimental/c-cpp/manager.py

Introspector recently changed the way all functions are stored. This adjusts the from-scratch set up to use this.
No need for trial builds here.

experimental: adjust to recent introspector updates

---

llm_toolkit/models.py

Our project is [not allowed to use version 0514](https://pantheon.corp.google.com/logs/query;aroundTime=2024-06-21T07:21:22.542363283Z;cursorTimestamp=2024-06-21T07:21:22.542363283Z;duration=PT1H;pinnedLogId=2024-06-21T07:21:22.542363283Z%2Fg942n23o7grufv34;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22oss-fuzz%22%0Aresource.labels.location%3D%22us-central1-c%22%0Aresource.labels.cluster_name%3D%22llm-experiment%22%0Aresource.labels.namespace_name%3D%22default%22%0Alabels.k8s-pod%2Fbatch_kubernetes_io%2Fcontroller-uid%3D%2296d19a6d-9712-40cb-806f-0e99152e294f%22%20severity%3E%3DDEFAULT%0Atimestamp%3D%222024-06-21T07:21:22.542363283Z%22%0AinsertId%3D%22g942n23o7grufv34%22;storageScope=project?project=oss-fuzz):
``` …
```

Revert Gemini 1.5 model.

---

data_prep/introspector.py

FI added an option for oracles to only return functions with cross references. This is convenient to avoid e.g. rewritten `main` functions, and is also convenient for cases where the prompt integrates features that are based on cross-references. This PR makes it possible to leverage this feature.
Ref: https://github.com/ossf/fuzz-introspector/pull/1614

introspector: add option for only collecting oracles with references

---

report/templates/benchmark.html
report/web.py

Currently, when generating reports using the command outlined [here](https://github.com/google/oss-fuzz-gen/blob/main/USAGE.md#results-report), the sample pages are named solely by `sample_id`, with no file extension. This results in the browser prompting users to download the file, named like '01', instead of displaying it as an HTML page when they click the link. This behavior occurs because the links lack the `.html` suffix, which is crucial for web browsers to recognize and render the content appropriately.
To address this issue, I have modified the code in `.report/web.py` and updated the templates in `report/template/benchmark.html` to automatically append the .html suffix to the filenames. This change ensures that the generated links function correctly, allowing the HTML pages to …

Fix for Incorrect File Extension in Generated Report Links

---

llm_toolkit/prompt_builder.py

This PR fixes a bug in JVM prompts creation which use a wrong template file for some argument types.

JVM: fix bug for using wrong template

---

experiment/benchmark.py
llm_toolkit/prompt_builder.py
prompts/template_xml/jvm_problem_constructor.txt
prompts/template_xml/jvm_problem_method.txt

This PR adds new elements for JVM prompt building. The new elements include the source code of the target function and also the source code of cross-reference which directly invokes the target method. This information is added to the existing prompts for JVM projects to provide better information for the LLM to generate better fuzzing harnesses.

JVM: Add logic to build prompts with reference to source code

---

prompts/template_xml/jvm_requirement.txt

This PR fixes a bug in JVM prompts creation which uses a wrong mapping name in one of the template.

JVM: Fix wrong template mapping name

---

experiment/builder_runner.py

There is a bug in `_contains_target_jvm_method` function which fails all constructors because the constructor name `<init>` never exists in the harness generated by the LLM model. This PR fixes that by retrieving the class name for locating the target constructor call in the generated harness.

JVM: Fix bug in discovering of JVM constructor target

---

prompts/template_xml/jvm_specific_data_filler.txt

The prompt suggests if a random primitive class array is needed as an argument, the ArrayUtils.toObject() method is called to box the primitive array. This requires an extra Apache-commons-lang library which may not exist in most JVM projects in OSS-Fuzz. Thus this case the generated fuzzers with the use of ArrayUtils fail to compile. This PR fixes that by replacing the suggestion with something local approach.

JVM: Fix prompt for primitive class array

---

prompts/template_xml/jvm_specific_data_filler.txt

This PR fixes the prompts for JVM method argument type suggestion on java.lang.Object instance.

JVM: Fix argument type suggestions in prompts

---

llm_toolkit/prompt_builder.py

For unknown reasons, when a random java.lang.Object instance is needed for method arguments, the LLM model always generates the needed instance with `FuzzedDataProvider::consumeObject()` or `FuzzedDataProvider::getObject()`. These two methods are not valid and never exist. Similar case happens for integer instance. the LLM model use a non-exist `FuzzedDataProvider::consumeInt(int)` for integer data generation.
This PR adds a temporary fix to replace the call to these methods with a valid one.
The `FuzzedDataProvider::consumeObject()` or `FuzzedDataProvider::getObject()` are replaced by `FuzzedDataProvider::consumeString(int)` as String is one of the subclasses for the Object instance.
The `FuzzedDataProvider::consumeInt(int)` is replaced by `FuzzedDataProvider::consumeInt(int, int)` for …

JVM: Fix non-exist method call

---

data_prep/introspector.py

This PR adds new introspector query to obtain list of existing source file paths for JVM project. This list of information helps to filter out-of-scope method candidates during data preparation step.

JVM: Fix interesting files handling

---

experiment/builder_runner.py

Function `operator` is a special case that can be followed by special chars like `++`.
This PR includes that in the regex.
For example, the following line uses `++`, but was not parsed by the current regex:
```C++
// Iterator<std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<bool, std::__1::allocator<bool> >&> & iter::impl::Compressed<std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<bool, std::__1::allocator<bool> >&>::Iterator<std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<bool, std::__1::allocator<bool> >&>::operator++(Iterator<std::__1::vector<int, std::__1::allocator<int> > &, std::__1::vector<bool, std::__1::allocator<bool> > &> *);
it++;
```

Fix regex to parse function name when checking if it is called in the fuzz target

---

data_prep/introspector.py
data_prep/project_context/context_introspector.py
llm_toolkit/code_fixer.py
llm_toolkit/prompt_builder.py
prompts/template_xml/fixer_instruction.txt
prompts/template_xml/fixer_problem.txt

LLM insists on including non-existent files, likely because LLM _thinks_ that's necessary (for the function-under-test) or does not know what's the correct alternatives
```
isc_lex_gettoken.c:5:10: fatal error: 'isc/boolean.h' file not found
5 | #include <isc/boolean.h>
|          ^~~~~~~~~~~~~~~
```
This PR specifically asks LLM to remove that incorrect statement (and suggest any existent alternatives).

Ask LLM to remove `#include 'non-existent filepath` and suggest alternatives

---

llm_toolkit/code_fixer.py
llm_toolkit/prompt_builder.py

This sometimes happens when a C++ project has a C fuzz target.
The error message may confuse LLM, so I added direct instructions.

Ask LLM to not use FDP in C fuzz targets

---

experiment/evaluator.py
llm_toolkit/prompt_builder.py
prompts/template_xml/jvm_requirement.txt
run_one_experiment.py

This PR includes the needed name in the prompts to allow the LLM model to generate a fuzzing harness with the correct name. This removes the need to replace the name afterwards. This change could avoid errors when the class name is used by other logic in the generated fuzzing harness class which has not been updated.

JVM: Fix name of fuzzing harness

---

llm_toolkit/prompt_builder.py
run_one_experiment.py

This is similar to the C specific prompt builder. It's likely more fields will be used from the benchmark and this refactors things before we unnecessarily explode the number of arguments to the prompt builder.

jvm: simplify prompt builder by using benchmark

---

data_prep/introspector.py
llm_toolkit/prompt_builder.py
prompts/template_xml/c-priming.txt

Also uses it in the C-targeted prompt. In essence an alternative to having this in the prompt is avoiding having these in the prompt and just including the header files mechanically, but I'll explore that later for now.
This has been tested locally on a myriad of C projects, so suggest leaving the CI experimentation for now (I'll add the ability to apply a given model shortly)

introspector: add api to get header files where a function is likely declared

---

data_prep/introspector.py

Adds a new option from fuzz introspector that makes it possible to select benchmarks only if they are determined to be declared in a header file. This is part of a wider effort in more accurately descriping the header files to include in a given harness.
Ref: https://github.com/ossf/fuzz-introspector/pull/1624
Ref: https://github.com/ossf/fuzz-introspector/pull/1641

introspector: force header-only targets

---

data_prep/project_context/context_introspector.py
experiment/builder_runner.py
llm_toolkit/code_fixer.py
llm_toolkit/prompt_builder.py
prompts/template_xml/fixer_priming.txt

1. Always import built-in libraries first to avoid 'unknown type name' error.
2. Fix header files by replacing them with the one with the same name (but different path).
3. Make `goto` statement optional so that the prompt is more focused.

More fixes for headers

---

data_prep/introspector.py

Create benchmarks using FI's optimal target analysis.
Ref:
https://github.com/google/oss-fuzz-gen/issues/356#issuecomment-2178716065

introspector: add optimal target API

---

llm_toolkit/prompt_builder.py

This PR fixes a bug in the wrong source code retrieval logic for function cross reference.

JVM: Fix bug on cross reference code retrieval

---

llm_toolkit/prompt_builder.py
prompts/template_xml/jvm_base.txt
prompts/template_xml/jvm_problem.txt
prompts/template_xml/jvm_problem_constructor.txt
prompts/template_xml/jvm_problem_method.txt

This PR revamps the JVM prompt template structure by grouping and organising different method properties into subtags to allow the LLM model to pick up the necessary information in a non-confusion way.

JVM: Revamp prompt structure

---

data_prep/introspector.py

This PR adds a new introspector query to the function-with-matching-return-type api which retrieves a list of functions and constructors that returns the needed type of object.

data_prep: Add query for /api/function-with-matching-return-type

---

report/web.py

When running experiments locally the workflow is to continuously rebuild the static pages while having a http server launched. This is a bit inconvenient. This commit adds an option to the web module such that both a http server is launched and the static generator continues to generate files as long as the http server is launched.

report: add option for continuous report serving

---

data_prep/introspector.py

I've run into several regressions during API development that's causing timeout issues, and having the logs ready makes debugging a lot easier.

introspector: show url when timeouts happen

---

llm_toolkit/prompt_builder.py
prompts/template_xml/jvm_arg_description.txt
prompts/template_xml/jvm_generic_arg_description.txt
prompts/template_xml/jvm_object_arg_description.txt
prompts/template_xml/jvm_simple_arg_description.txt

This PR revamps the argument suggestion in prompts for JVM method. More details about creation of some types of arguments (including java.lang.ObjecT) used in the method invocation has been added to allow LLM generate a better fuzzing harness with random data and correct argument types.

JVM: Add handling suggestion for simple arguments

---

.pylintrc

Enable `Pylint` `f-string` checking.

Reminder us using f-string

---

report/common.py

There's a handful of warnings when changing things in report/common.py and this fixes them all.

report: fix presubmit warnings

---

README.md

We recently added gpt-4o support (https://github.com/google/oss-fuzz-gen/pull/398) and a number of other models in addition to the ones on the list are also available.

README: update model list

---

experiment/oss_fuzz_checkout.py
run_all_experiments.py
run_one_experiment.py

This is useful during development purposes where it's convenient being
able to adjust the OSS-Fuzz projects' folders, e.g. to test hypotheses.

core: enable use of dedicated oss-fuzz folder

---

experimental/c-cpp/build_generator.py
experimental/c-cpp/manager.py
experimental/c-cpp/runner.py

Refactors the from-scratch logic by:
- Adding a container for build workers
- Removing unused code
- Facelifting string formatting since it was added to the CI
Note, in the `manager` and `build_generator` we can't remove the use of `List` and `Dict` since it relies on the Python from OSS-Fuzz, which hasn't migrated to `list` and `dict` yet.
This is working towards https://github.com/google/oss-fuzz-gen/issues/450

experimental: refactor to simplify and compartmentalise

---

helper/result_string_search.py

Now we can get the direct URLs to the report, e.g.,
```url
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr//2024-07-11-465-dg-comparison/sample/output-ada-url-ada_can_parse_with_base/08.html
```
via:
```bash
python helper/result_string_search.py -s "undefined reference" -r 2024-07-11-465-dg-comparison/sample/ -u https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/
```

Simpler bucket url access for `result_string_search.py`

---

ci/ci_trial_build.py

The comment parser sometimes include empty string as a command line argument, which breaks python's argparser in [`request_pr_exp.py`](https://github.com/google/oss-fuzz-gen/blob/main/ci/request_pr_exp.py).
This PR removes empty strings from the command parsed from the comment.

Filter empty string in comment

---

prompts/template_xml/jvm_base.txt
prompts/template_xml/jvm_problem.txt

This PR fixes the prompt template by removing the mentioning of the Jazzer framework.

JVM: Remove mentioning of Jazzer in JVM prompts

---

report/web.py

This makes it possible to run multiple runs in parallel both with report generation.

report: make it possible to specify port

---

experimental/manual/prompter.py
llm_toolkit/code_fixer.py
llm_toolkit/crash_triager.py
llm_toolkit/models.py
run_one_experiment.py

The main reason for this is that the `generate_code` does not really generate any code but rather it queries a given LLM using a specified prompt. Since we now have prompts of various sort, I feel it might be a bit misplaced the name. This could also make it a bit more clear which API to use if you're working on using LLMs for tasks other than explicit code generation.
This came up while doing https://github.com/google/oss-fuzz-gen/pull/479 where one consideration was to have the LLM generate a corpus explicit without going a seed-corpus-by-way-of-python generation.
Ref: https://github.com/google/oss-fuzz-gen/issues/482

Rename gen code to query llm

---

experimental/manual/oss_fuzz_vuln_prompt.py

Drive-by, following https://github.com/google/oss-fuzz-gen/pull/478#discussion_r1677235224

Fully exclude `/usr/` paths.

---

.github/workflows/osv-scanner-pr.yml
.github/workflows/osv-scanner-scheduled-push.yml

Avoid showing irrelevant action on PRs:

Separate osv-scanner workflows so that the action for scheduled and push will not appear on PRs

---

data_prep/introspector.py
data_prep/parse_training_data.py
data_prep/project_context/context_introspector.py
data_prep/project_context/context_retriever.py
data_prep/project_src.py
data_prep/project_targets.py
data_prep/target_collector.py
experiment/builder_runner.py
experiment/evaluator.py
experiment/fuzz_target_error.py
experiment/oss_fuzz_checkout.py
experiment/textcov.py
llm_toolkit/code_fixer.py
llm_toolkit/models.py
llm_toolkit/prompt_builder.py
run_all_experiments.py
run_one_experiment.py

We use logging in multiple formats:
- logging.info/debug/..
- print(
- write to files
It's fairly inconsistent. So am unifying it in a more Pythonic way. The format also makes it easier to track performance of the tool as we can find bottlenecks by looking at the logs.

unify logging

---

experiment/builder_runner.py
experiment/evaluator.py
experiment/textcov.py

This PR fixes multiple bugs that cause problems in calculating line coverage diff for the JVM projects.
The bugs are listed below.
1. The path to finding the existing coverage report (jacoco.xml) is wrong, making the logic always compare with an empty report when calculating for line coverage diff. This PR adds a new functions to retrieve and parse the existing coverage report correctly.
2. The interpretation logic for the JVM coverage report on array-type arguments or empty arguments is wrong, resulting in a non-matching method name when merging the coverage report. This PR fixes the java name and argument interpretation to get a correct method signature as identifiers when combining and subtracting coverage reports.
3. The subtraction of that line diff values between the existing …

JVM: Fix multiple bugs in JVM coverage calculation

---

data_prep/introspector.py
llm_toolkit/prompt_builder.py
run_one_experiment.py

While working on https://github.com/google/oss-fuzz-gen/issues/494 I
need to adjust a few things wrt. Benchmarks, as the test-to-harness
logic doesn't fit the benchmark abstraction entirely. This commit is a
step towards simplifying some of the code around benchmarks. I also
removed some code that was no longer used, e.g. `manual_fix` in
`run_one_experiment.py`.

cleanup some benchmark related code

---

data_prep/introspector.py

There is a wrong indentation in the _select_functions_from_oracles function. This wrong indentation causes the function to always return a function list from the first oracle in the provided `target_oracles` list only. This PR fixes the indentation bug.

data_prep: Fix bugs in introspector query

---

llm_toolkit/prompt_builder.py

The function misses an `s` causing the logic to be the default, which is not as intend. This fixes the name so the post processing logic is called.

c-specific builder: fix typo in post_process_generated_code

---

data_prep/introspector.py

It is found that the query of the introspector oracles are customised for C/C++ projects. This PR adds an additional function to process the query of the introspector oracles for JVM projects which works in a different manner.

JVM: Fix introspector querying logic

---

experimental/c-cpp/templates.py

The backslashes need to be part of the resulting file, otherwise we just get very long lines

experimental: fix multi-lines in templates

---

ci/k8s/pr-exp.yaml
ci/request_pr_exp.py
llm_toolkit/code_fixer.py
llm_toolkit/models.py
report/docker_run.sh
run_one_experiment.py

This PR:
1. Sets back the default temperature to 0.4.
2. Continues #448 to allow different temperatures for fuzz target samples.
I will re-run a full exp to validate their effect.
The recent [08-03 report](https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-08-03-weekly-all/) contains regressions due to model inadequacies, such as:
```c++
fuzz/parse.cc:13:21: error: calling 'parse_url<url>' with incomplete return type 'url'
13 |   ada::url result = ada::parser::parse_url(url, base_url);
```
This is likely because we [increased the temperature](https://github.com/google/oss-fuzz-gen/pull/448/files#diff-0d648b28bb6b85213eb0ff1c3954edd4b710ff8b219eb7dc89b294108dfedb3eL52-R52). Maybe code generation needs to be more strict and less random?
Also #448  did not pass `VARY_TEMPERATURE` to …

Set back temperature to 0.4

---

ci/request_pr_exp.py

To avoid repeatedly manually adding `-f` in `/gcb exp` commands.

Always delete old bucket dir and GKE job of the same name in PR experiments

---

report/docker_run.sh

[08-07](https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-08-07-weekly-all/) experiment, with temperature 0-0.4, did not perform well either.
Given we have a weekly experiment scheduled tmr and only very few temperature values were untested, I'd propose doing a "grid search" on the rest.
Current ranking is:
1. [07-06](https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-07-06-weekly-all/) with constant temperature 0.4: 1042 successful builds.
2. [08-03](https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-08-03-weekly-all/) with constant temperature 1: 960 builds.
3. [08-07](https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-08-07-weekly-all/) with vary temperature 0-0.4: 898 builds.
The new experiment will test 0.5-0.9 so that we have some data for each.

Grid-search Temperature

---

.pylintrc

Using lazy % formatting in logging functions provides better thread safety as string evaluation is done in the logging module.

Ask `pylint` to check lazy logging

---

data_prep/introspector.py
experiment/benchmark.py
llm_toolkit/prompt_builder.py
prompts/template_xml/jvm_requirement.txt

There are some properties in the benchmarks that only exist for JVM projects. In the current logic, these properties are being added to the benchmark class and only JVM projects will use them. This PR reduces the size of benchmarks by removing these properties from the benchmarks. Instead, these properties are lively queries from the introspector new API without the need to store them in the benchmark objects. 
In addition to the two properties (exceptions and is_jvm_static) for JVM projects, a third property is also added to indicate if the target method is a resource-type object (implements AutoClosable) that needs to be closed after use. This helps to reduce possible OOM in generated fuzzing harnesses because of memory leaks from unclosed resource objects. This is the replacement of …

JVM: Revamp JVM specific properties retrieval for prompt generation

---

report/templates/index.html

The new project summary table uses the sortable-table class but the current javascript logic only behaves well in the context of a single sortable-table. Since we now have two sortable-tables we need to adjust the javascript logic to handle this. The primary way of resolving this is making sure the sorting logic gets a hold of the right table as opposed to considering all `th` values as part of the same table.

report: make project summary table sortable

---

experiment/oss_fuzz_checkout.py

This allows us to reuse the cached images over multiple experiments, without having to rebuild at any point.

oss-fuzz-checkout: reuse cached image over multiple runs

---

experiment/benchmark.py

Otherwise the naming looks weird in the html report because we rely on splitting `-`. As such, when a testfile has `-` in the name it goes into the project name in the web report. This fixes it.
Ref: https://github.com/google/oss-fuzz-gen/blob/feb19caf287d0a1cbdd13af70e56b3f91997a7c9/report/common.py#L513

benchmark: fix naming to avoid web report inconsistency

---

report/common.py
report/templates/crash.json
report/templates/sample.html

This PR displays the triage prompt on the web, making it easier to read and evaluate the factors affecting LLM triage.

Display triage prompt on web

---

experiment/evaluator.py
experiment/oss_fuzz_checkout.py

This makes it possible to run OSS-Fuzz-gen on projects that are in a local OSS-Fuzz folder, but that are not in upstream OSS-Fuzz. This needs to use a local deployment of Fuzz Introspector.
Will follow-up with PRs for experimental that merges the two with scripts.
Ref: https://github.com/google/oss-fuzz-gen/issues/498

make it possible to run projects not in OSS-Fuzz upstream

---

llm_toolkit/models.py

Added classes to support Azure's GPT model usage, which inherits from the class `GPT` according to the tutorial of Azure: 
[Create a new Python application](https://learn.microsoft.com/en-us/azure/ai-services/openai/quickstart?tabs=command-line%2Cpython-new&pivots=programming-language-python#create-a-new-python-application)
Our changes: 
- overwrite the function `query_llm`, since the client is a bit different from the original GPT calling.
- overwrite the function `estimate_token_num` because we added a suffix (i.e., `-azure`) for the model name to distinguish the GPT model from the original GPT model (`gpt-3.5-turbo`, `gpt-4`, and `gpt-4o`). 
We have tested it in my local environment, it works well for all of the above Azure's GPT models.
Hope it helps.

Add support for Azure's GPT model

---

experimental/c-cpp/manager.py
experimental/c-cpp/templates.py

This will make it easy to migrate any number of harnesses into the generated project

experimental: make harness build cmd into a loop

---

report/common.py
report/templates/crash.json
report/templates/sample.html

From #538: This PR displays the triage prompt on the web, making it easier to read and evaluate the factors affecting LLM triage.

Display triage prompt on web (#538)

---

data_prep/introspector.py
llm_toolkit/prompt_builder.py

This makes it possible to extract a subset of test, for example when a test file is too long.

test-to-harness: use new API endpoint to extract test code

---

report/web.py

Links are not working for Java coverage reports because of mismatch with report/index.html

report: fix java coverage links

---

data_prep/introspector.py

The goal is to phase out the project_src.search_source strategy
by pushing this to FI. I have set it as optional for now while
we're awaiting an OSS-Fuzz update on FI. However, this improves
performance, since we don't have to search through /src/ for
each benchmark, and we can also push much of the e.g.
bazel-recognition logic into FI.

introspector: introduce harness source/executable retrieval via FI 

---

data_prep/introspector.py

The introspector query for jvm return type searching has a wrong parameter name. This PR fixes that.

JVM: Fix wrong query parameter bug

---

experiment/evaluator.py

This PR fixes the handling of missing JVM coverage report. The new logic returns an empty Textcov object instead of throwing a RuntimeError. The new setting allows processing of new OSS-Fuzz integration which does not have existing coverage reports.

JVM: Fix handling for empty coverage report

---

llm_toolkit/prompt_builder.py

This PR fixes a bug in exception handling for JVM prompt generation. The return value of `introspector.query_introspector_function_props()` could be an empty dictionary, causing a `KeyError` when attempting to access the first items. The fix adds fail-safe logic for when the dictionary is empty and directly provides a default empty list for processing.

JVM: Fix bug in exceptions list handling

---

README.md

The recent undisclosed issue was based on test-to-harness migration and not the default Prompt builder/far-reach-low-coverage oracle, so changing that.
We have a number of settings now, but I think prompt builder + target oracle may be the most impactful on the outcome of an auto-generation run.
I kept the links to the prompt texts, but it's not ideal since it just links to the folder with a lot of prompt files.
To this end, I suggest we refactor the specific prompt builders out into individual modules so we can provide a reliable link to them (while also being a bit nicer to read I think).

README: add more context to the trophies

---

data_prep/introspector.py

There's no functions to extract.

introspector: do not extract functions from test-migration

---

experiment/textcov.py

This PR fixes a bug in JVM coverage caluclation which skip the coverage calculations for constructors.

JVM: Fix missing coverage for constructors

---

data_prep/introspector.py

This PR fixes a bug in the `_get_data` function used for retrieving the necessary data from an introspector response. It was found that some introspector queries could return an empty list, empty dictionary, or boolean False as data. This causes the current check to be unable to distinguish between a missing field in the response, an empty list, or a boolean False value. This PR addresses the issue.

introspector: Fix bug in introspector response data retrieval

---

data_prep/project_src.py

This PR fixes a bug in local project building of Java and python projects for benchmark generation, where the fuzzing language is wrongly fixed to `c++`.

Fix bug of wrong fuzzing language for Java and python projects

---

experimental/jvm/generate_projects.py
experimental/jvm/utils.py

The Python script in the `experimental.jvm` package is not intended to be invoked by the core OFG logic. Instead, it is meant to be executed by the `run_e2e.sh` script located in the same directory. Therefore, if the package name `experimental.jvm` needs to be changed as done in #604, the `sys.path` must be set to the core OFG base path. This PR implements that change.

Fix package missing bug

---

llm_toolkit/prompt_builder.py

We have a function in `oss_fuzz_checkout` which extracts the main_repo of a given project. We dont need these utilitiy functions in the prompt builders.

prompt-builder: use utility to get main_repo

---

report/docker_run.sh

Otherwise we can pass an empty string which breaks the argument passing.

Don't quote `$AGENT_ARG` in docker_run.sh

---

ci/k8s/large-pr-exp.yaml
ci/request_pr_exp.py

This can be triggered by passing `--large`, which changes the cluster and CPU/memory requests and parallelism.

Support large PR experiments.

---

experiment/builder_runner.py

This is meant to be used for tagging binaries I believe. We already do this in Fuzz Introspector in order to correlate source code with binaries, so I assume in that sense we already have support this as well.

builder-runner: remove unused logic

---

experiment/builder_runner.py

Refactors code-reuse and using correct helper functions. Shortens the complexity of the larger `get_coverage_local` function.

builder-runner: refactor and cleanup local coverage extraction

---

experiment/builder_runner.py
report/docker_run.sh
report/web.py

This will make post processing of results easier, also when downloading the reports locally.

builder_runner: store summary.json in workdir in cloud runs

---

run_all_experiments.py

- Adjusts coverage gain to show the actual coverage gain with respect to the existing coverage report. Previously the aggregated data simply showed the total coverage achieved.
- Makes the reading independent of the results array. The goal here is to make it asynchronously since we experienced issues where some benchmark runs would finish but not show up in the aggregate table.

run_all_experiments: fix coverage sync and wrong aggregate coverage gains measure

---

benchmark-sets/bug-fdp-consume-buffers/htslib.yaml
benchmark-sets/bug-fdp-consume-buffers/libxml2.yaml
benchmark-sets/bug-fdp-consume-buffers/lodepng.yaml
benchmark-sets/bug-fdp-consume-buffers/opus.yaml
benchmark-sets/bug-fdp-consume-buffers/snappy.yaml

This is useful for testing mititgations and also regressions. The benchmark has been annotated with links to the bugs.

benchmark-sets: add buggy benchmark

---

data_prep/introspector.py
experiment/benchmark.py
helper/update_comp_benchmarks.py
run_all_experiments.py
run_one_experiment.py

This fixes the discrepancy mentioned here https://github.com/google/oss-fuzz-gen/pull/645#issuecomment-2373714631. Saving the benchmark for each result has additional benefits than supporting the aggregate. It makes it easier to save results when auto-generation of benchmarks are used as part of the experiment (I use this a lot).
Notice not the full benchmark `.yaml` from `benchmarks-set/...` is set, but only the actual (one function or one test file) is saved per result dir.

save benchmarks in results and use for aggregate coverage calculation

---

report/web.py

Introduced following the addition of textcov to the workdir in https://github.com/google/oss-fuzz-gen/pull/638
This caused reports to individual benchmarks run to have wrong links, e.g.
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-09-21-638-d-cov-21-minor-for-ci/benchmark/output-htslib-bcf_index_build/index.html

report: fix bug for coverage links

---

experiment/builder_runner.py

This PR fixes the bug in using heuristic methods to determine whether the fuzz driver has a problem. This sub-rule was originally intended to traverse each stack frame in the first crash stack until it finds a stack frame containing the "LLVMFuzzerTestOneInput" function, and other stack frames before this stack frame do not contain functions of testing proj. For the task of determining whether the function in the stack frame belongs to testing proj (i.e. function "_stack_func_is_of_testing_project"), we originally planned to let LLM make the judgment. Since adding this part of logic to the original framework makes the code redundant and complicated, we will implement this logic in the agent framework. The agent code will be submitted in the next few days.

Fix bug in triaging stack func

---

experiment/builder_runner.py
experiment/oss_fuzz_checkout.py

Changes the of cached images to align with changes from https://github.com/google/oss-fuzz/pull/12549
These images were causing issues unless we specify the explicit entrypoint when running the harnesses, so adjusted that as well.

cache: align names with oss-fuzz and specify entrypoint explicitly

---

llm_toolkit/prompt_builder.py
prompts/template_xml/test_to_harness_priming.txt

- Fixes some issues there were with header file inclusion in the prompt (it used the wrong variable, so the string was wrong)
- adds a sample harness from the actual repository
- adds a list of all headers

prompts: extend test-to-harness prompting

---

data_prep/introspector.py

Log if not, and return without causing index-out-of-bounds exception. This is needed when running larger experiments and benchmarks are generated on the fly, in the event some harness pairs are not found.

introspector: check if harness/source pairs are valid

---

agent/base_agent.py
agent/prototyper.py
common/cloud_builder.py
logger.py
report/common.py
report/templates/base.html
report/templates/sample.html

To make the LLM interactions clearer. Prompts are coloured with a slight pink background, and responses are moved to the right side with a slight green background. 
Part of #676.
Also stop propagating chat logging to the root logger (to avoid duplicate output). 
This PR also adds some workarounds for when `fixed_targets`, `raw_targets` don't exist in the results dir for agent runs. This can happen when we download a results dir from GCS, because empty dirs are not uploaded. 
Example:

Better format agent chat history in reports.

---

experiment/oss_fuzz_checkout.py

To match https://github.com/google/oss-fuzz/pull/12676.
This gets rid of an unnecessary inconsistency.

Update ofg cached image name.

---

experiment/oss_fuzz_checkout.py

This works but once we support the replayable scripts we need further adjustments.

oss_fuzz_checkout: support local ccache builds

---

experiment/oss_fuzz_checkout.py

We weren't keeping the ARG, WORKDIR lines.
ARG is necessary for obvious reasons since we are relying on injecting
the base image at runtime.
WORKDIR is required for: https://github.com/google/oss-fuzz/blob/edfa6730fa9f1dca77dd27c0b3a643171e082950/infra/build/functions/build_project.py#L229

Fix Dockerfile rewrite for using cached builds.

---

agent/prototyper.py
llm_toolkit/models.py
llm_toolkit/prompt_builder.py
prompts/agent/prototyper-priming.txt
prompts/example/dns_message_parse.c
prompts/tool/container_tool.txt

Restructure and decouple prompts, add clearer instructions and steps.
Although we should keep this, there are still problems that cannot be fixed by simple prompting.
E.g., LLM cannot figure out which `*.o` files to add to include the function-under-test, even though there are examples from other fuzz targets.
I will do this via more agents later.

Organize prototyper and container tool prompts

---

stage/execution_stage.py

@maoyixie pointed out that local agent experiments have conflicts in project names due to using the incorrect sample/trial ID.
This results in trials re-using the fuzz target and build script from earlier trials.
This PR fixes by correcting the code to get the trial ID.

Use the correct trial ID

---

run_all_experiments.py

This makes us create fresh instances for every experiment. 
Speculative fix for some issue we're seeing with hanging experiments.

Try setting maxtasksperchild=1

---

ci/k8s/pr-exp.yaml

Verified that this enables gdb/ptrace inside the container.

Make PR experiment containers privileged too.

---

run_all_experiments.py

Per
https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool.apply_async, callbacks should return immediately or they will otherwise block the entire Pool from making progress.
For large experiments, this is likely causing problems causing our throughput to slow to a crawl as the experiment runs, as every single benchmark experiment finishing requires this expensive calculation. 
From debugging with GDB on
https://github.com/google/oss-fuzz-gen/pull/692, it looks like a large number of worker processes are stuck waiting to report results:
```
(gdb) py-bt
Traceback (most recent call first):
File "/usr/lib/python3.11/multiprocessing/synchronize.py", line 95, in __enter__
return self._semlock.__enter__()
File "/usr/lib/python3.11/multiprocessing/queues.py", line 376, …
```

Don't call extend_report_with_coverage_gains in apply_async callback.

---

README.md

They were very very out of date.

Update coverage stats.

---

agent/base_agent.py
agent/prototyper.py

Previously, when the LLM response included both bash commands and a conclusion, we ignored the bash command and compiled the fuzz target in the conclusion alone. This approach is suboptimal, as conclusions may be premature, and the bash command often provides useful context to refine them.
To improve accuracy, we should prioritize the bash command when both are present in a response.
A more robust solution would involve structuring tasks to prevent mixed responses (e.g., using task-focused agents). But until then, prioritizing bash commands in mixed responses provides a fallback/default solution.

Prioritize Bash if LLM responses both Bash and Conclusion

---

benchmark-sets/all/hermes.yaml
benchmark-sets/all/sleuthkit.yaml
benchmark-sets/all/stb.yaml
helper/diff_target.py

... and a script to find mismatched binary names between benchmark sets.

Fix incorrect binary names

---

common/cloud_builder.py

Previously, cloud build pulls an agent image that I manually uploaded to artifact registry.
However, this will fail when we update dependencies (e.g., upgrade python packages) in PRs.
This PR builds the image with the PR source code so that its agent image is always up-to-date.

Build agent image in cloud build

---

agent/base_agent.py
agent/prototyper.py
logger.py
pipeline.py
run_one_experiment.py
stage/base_stage.py

The original code ([_fuzzing_pipelines](https://github.com/google/oss-fuzz-gen/blob/c9f87defe821ab66f123b7730b59eb2a93c6608b/run_one_experiment.py#L336), [_fuzzing_pipeline](https://github.com/google/oss-fuzz-gen/blob/c9f87defe821ab66f123b7730b59eb2a93c6608b/run_one_experiment.py#L321), [get_trial_logger](https://github.com/google/oss-fuzz-gen/blob/c9f87defe821ab66f123b7730b59eb2a93c6608b/logger.py#L126)) will cause multiple threads in the thread pool to share a logger. Now use threading.local() to create a separate logger for each thread.

Fix multiple threads share one logger

---

llm_toolkit/prompt_builder.py
prompts/template_xml/jvm_requirement_test_to_harness.txt

This PR fixes the JVM test-to-harness prompt creation to add in sample harness for reference.

[JVM] Add harness sample code for JVM test-to-harness approach

---

run_all_experiments.py

The original result of using '--hep' is as follows:
```
-lo LOG_LEVEL, --log-level LOG_LEVEL
Sets the logging level. Options available: [{LOG_LEVELS}]
```
The result of using '--hep' after the repair is as follows:
```
-lo LOG_LEVEL, --log-level LOG_LEVEL
Sets the logging level. Options available: debug, info
```

Fix that specific log levels are not displayed when using --help

---

llm_toolkit/prompt_builder.py
prompts/template_xml/jvm_requirement_test_to_harness.txt

This PR adds consideration of needed import statements to LLM prompts for reference on JVM test-to-harness approach.

[JVM] Add import statements processing for test-to-harness prompt

---

llm_toolkit/prompt_builder.py
prompts/template_xml/jvm_requirement_test_to_harness.txt

This PR fixes the prompts for jvm test-to-harness approach to add in other import statement in the prompts for reference. This help LLM to include more necessary import statements to the generated harness.

[jvm] Include other import statements for test to harness approach

---

llm_toolkit/prompt_builder.py
prompts/template_xml/jvm_requirement_test_to_harness.txt

This PR fixes the logic for jvm test-to-harness to provide references of some methods suggestions for LLM.

[JVM] Add logic to add suggested targets

---

prompts/template_xml/jvm_requirement.txt
prompts/template_xml/jvm_requirement_test_to_harness.txt

This PR fixes the prompts for JVM approach to avoid asserts and printing statements being added to the fuzzing harness.

[JVM] Exclude asserts and printing statements

---

llm_toolkit/prompt_builder.py
prompts/template_xml/jvm_requirement_test_to_harness.txt

This PR fixes the import statement suggestion logic for JVM projects. This PR also add post-processing for JVM test-to-harness approach to do some minor fixes to the generated harness.

[JVM] Fix import statement suggestion

---

experiment/builder_runner.py
experiment/evaluator.py
llm_toolkit/code_fixer.py
llm_toolkit/prompt_builder.py
prompts/template_xml/jvm_requirement_error_fixing.txt
run_one_experiment.py

This PR add back the retry logic for JVM when the first generated harness is failed to build.

[JVM] Add retry logic for JVM

---

experiment/evaluator.py

This PR fixes the JVM retry logic to ignore run crashes as they are possibly legit bugs in JVM projects.

[JVM] Ignore run error for JVM projects

---

data_prep/introspector.py
experiment/evaluator.py
llm_toolkit/code_fixer.py
llm_toolkit/prompt_builder.py
prompts/template_xml/jvm_requirement_coverage_fixing.txt

This PR relocate the calculation of coverage total and coverage diff into the checking and retry loop. This fixes can then use the lively caluclated coverage diff to determine if the successfully build and run harness increase the project coverage or not. If it does not increase the project coverage, use the new retry logic prompts to ask LLM to help fixing the harness. The fixing of errors in generated harness as well as harness with no coverage increase are count together. After this fix, it increase the rate of successfully build and run for generated harness and make sure more of them could have help improveing  project coverage.
*Remark, this coverage feedback approach is currently only work exclusively for JVM projects.*

[JVM] Add retry logic for no coverage gain

---

benchmark-sets/all/gnutls.yaml

This is a tricky case because the old target path (`/src/libtasn1/fuzz/libtasn1_gnutls_der_fuzzer.c`) is indeed a fuzz target, but it was not used.
I found the new one and its corresponding binary with @jonathanmetzman's trick:
1. Add a magic string (`const volatile char* build_id = "BUILD_TRACKER_my_unique_identifier_123";`) to the fuzz target before compilation.
2. Find the binary with the string (`find /out -type f -executable -print0 | xargs -0 sh -c 'for file do if strings "$file" | grep "BUILD_TRACKER_" >/dev/null; then basename "$file"; fi; done'`) after compilation.
I reckon we can do this systematically and automatically:
1. Inject unique magic strings (e.g., `BUILD_TRACKER_my_unique_identifier_1`, `BUILD_TRACKER_my_unique_identifier_2`) to all c/c++ files containing …

Fix fuzz target source path and binary name in gnutls.yaml

---

benchmark-sets/all/hostap.yaml

Similar to #750, this is another tricky case where the old target path is indeed a fuzz target and seems to be compiled with all actual fuzz targets.
Found the correct fuzz target source path and binary name using the same trick as in #750.

Fix fuzz target source path and binary name in hostap.yaml

---

benchmark-sets/all/librawspeed.yaml

This is another strange case:
1. The project is [compatible](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#librawspeed) with FI.
2. FI API [did not report](https://introspector.oss-fuzz.com/api/harness-source-and-executable?project=librawspeed) any pair.
3. The trick from #750 works:
```bash
#!/usr/bin/env bash
FILES=$(find /src \
-type f \( -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.cxx' \) \
-not -path '*/aflplusplus/*' \
-not -path '*/fuzztest/*' \
-not -path '*/honggfuzz/*' \
-not -path '*/libfuzzer/*' \
-exec grep -l 'LLVMFuzzerTestOneInput' {} \;)
for file in $FILES; do
file_escaped=$(echo "$file" | sed 's/\//\\\//g')
sed -i "1i const volatile char* build_id = \"$file_escaped\";" "$file"
done
echo "build_id line inserted in all matched files."
```

Update fuzz target source file path and binary name of librawspeed.yaml

---

agent/base_agent.py

Sometimes LLM suggests a build script with comments-only when it wants to reuse the existing build script, e.g.,
```
<build script>
</build script>
```
This avoids confusing LLM to 'think' the build script works.
Returning `''` will make OFG use the existing build script.

Ignore comment-only build script

---

agent/prototyper.py

Because sometimes build script content uses HereDoc too, which often uses the most common EOF as end-of-file delimiter.

Replace build script content using a HereDoc with a unique EOF

---

.github/workflows/lint.yaml

To address recent failures from linter CI:
```bash
E: Unable to locate package python3.11-venv
E: Couldn't find any package by glob 'python3.11-venv'
E: Couldn't find any package by regex 'python3.11-venv'
```
This is likely due to the new Ubuntu version (noble) does not have `python3.11-venv`, but we don't have to install it anyway.

Fix "Couldn't find any package by regex 'python3.11-venv'"

---

experiment/oss_fuzz_checkout.py
helper/result_string_search.py

No performance change expected:
This PR only eases report analysis and avoids print useless docker image build logs.

Functional fixes

---

USAGE.md
data_prep/README.md

Found a few 404 as the project was removed from the comparison benchmark

Fix broken links to tinyxml2.yaml in docs

---

experimental/from_scratch/generate.py

`function.arg_names` is a python list. Looping it to get both the items and the index requires the enumeration function which is missing from the code. The original code works because the testing is only done on empty arg_names which does not trigger the loop. This PR fixes the bug.

from_scratch: fix enumeration bug

---

experimental/from_scratch/README.md

The `requirements.txt` step is no longer needed since https://github.com/ossf/fuzz-introspector/pull/2060

from-scratch: simplify installation

---

experimental/from_scratch/README.md

This PR fixes the README for the experimental from_scratch approach to included source file / line searching and JVM projects.

from_scratch: Fix README.md

---

data_prep/introspector.py

This PR fixes the detection of source file path for jvm projects to support the updated approach in Fuzz-Introspector.

JVM: Fix source file path for new FI

---

scripts/run-new-oss-fuzz-project/run-project.sh

To guarantee a higher chance of creating benchmarks for new projects

run-new-oss-fuzz-project: extend with additional default heuristic

---

results.py

When there are no RunResult object exists in the result_history because of all failing cases, the max function call will be failed. This PR fixes the bug by adding default value for the max function call.

bug: fix bug in empty coverage result

---

data_prep/project_src.py

The docker container created during local source copy from local is only used within the function. But it will result in docker container collision when it is running across multiple pipelines. This PR fixes the naming of the one-use docker container to add a timestamp suffix (and retry with random sleep when collision occur) to avoid docker container collision.

Add timestamp suffix to avoid conflict

---

experiment/builder_runner.py
experiment/workdir.py

Reasons:
1. We don't need `JCC` to parse and pass fuzz target build error messages (into `err.log`), because agents can capture and fix build errors in project's containers natively, without relying on `target_experiment.py`. Some err.log were empty anyway.
2. Agents can modify build script, hence we don't need JCC to add flags, add header files, or switch compiler (C/C++).
3. `JCC`'s heuristics cause build errors in some projects (e.g., `brpc`).

Disable JCC and the reliance of its err.log

---

agent/one_prompt_prototyper.py
agent/prototyper.py

The new approach force the function reference check on the built binary for LLVMTestOneInput and this is only valid for C/C++ projects. This make the prototyper check always failed for other language. This PR temporary skip that validation for other languages which the validation is not valid.

Fix validation for function reference

---

agent/prototyper.py
experiment/builder_runner.py
experiment/evaluator.py
experiment/oss_fuzz_checkout.py
llm_toolkit/prompt_builder.py
prompts/agent/prototyper-fixing.txt
prompts/agent/prototyper-priming.c.txt
prompts/agent/prototyper-priming.cpp.txt
prompts/agent/prototyper-priming.txt
prompts/tool/container_tool.txt
results.py
stage/execution_stage.py
tool/container_tool.py

Fixing some issues revealed by full agent experiments earlier:
1. [x] LLM-generated build scripts do not save fuzz target binary into the correct path.
2. [x] Use default build script in the code fixing prompt in this scenario:
1. The default build scripts builds successfully but failed other checks (i.e., reference), and
2. The LLM-generated build script does not work.
3. [x] Selectively use the default built script and the LLM-generated built script, depending which is better.
4. [x] Use different code-fixing prompts based on which built script and which result it is:
* default or LLM built script
* No reference, no binary, or compilation failure
5. [x] Backup human-writtent `/src/build.sh` to `/src/build.bk.sh` in agent's containers in case LLM wants to reuse it in the new build …

Fix Agent prompt and infra

---

report/compare_results.py

It is observed that the CI starting to failed because pandas.read_csv will failed wierdly if the file is too large. This PR fixes the read_csv logic to include the chunksize properties to split the reading into multiple times and concat them back afterward to avoid the errors.

Fix CI failing because of pandas csv fail

---

llm_toolkit/models.py

This PR follows #800 by adding chat_llm implementation for GPT models.

Add chat_llm implementation for GPT model

---

pyproject.toml

otherwise `fuzz-generator` complaints about missing module

pyproject: add results module

---

.github/helper/presubmit

I often run from a virtual environment that is not located in $GITROOT/.venv. This change enables using either or with presubmit.

presubmit: allow using existing virtual environment

---

experimental/c-cpp/runner.py

Otherwise we run into an exception when this evaluates to None.

c-cpp: Add default value for --max_successful.

---

agent/base_agent.py
llm_toolkit/prompts.py

OpenAIPrompt's get function will return a list of prompts with role and content instead of pure string. This will cause error in later bash result handling. This PR adds a new gettext() function in OpenAiPrompt to combine content string from multiple prompt to a single string for processing.

Fix prompt text return bug

---

llm_toolkit/models.py
run_all_experiments.py

Given an overlong prompt, we want to truncate it to:
```
<prompt short initial text>
...(truncated due to exceeding input token limit)...
<prompt long ending text>
```
Where `...(truncated due to exceeding input token limit)...` replaces sufficient prompt text so that the final prompt is within token limit.

Fix prompt truncation logic

---

agent/base_agent.py
ci/k8s/pr-exp.yaml
ci/request_pr_exp.py
report/docker_run.sh
run_all_experiments.py

Now we can customize the max number of agent rounds in PR experiments with `--max-round` or `-mr`.

Make number of rounds flexible in PR experiments

---

report/common.py
run_all_experiments.py

Modified the benchmark status determination logic in `common.py` to:
1. Added a new helper method `_get_expected_trials_count()` that scans benchmark directories to determine the total expected number of trials
2. Updated `match_benchmark()` to mark benchmarks as "Done" only when all expected trials are complete
Tested the solution by creating benchmarks in various states using a local script:
- Complete benchmark with all trials present and successful
- Partial benchmark with only some trials having results
- Failed benchmark with all trials present but some failing
Verified the status was correctly reported as "Running" for partial and failed benchmarks, and "Done" only for the complete benchmark
Fixes #721

Fix benchmark status reporting to accurately reflect trial completion

---

report/templates/base.html
report/templates/sample.html

Modified the report templates in `base.html` and `sample.html`:
- Added CSS styling for a two-column code display layout (line numbers + code content)
- Implemented a responsive code container with proper overflow handling for long lines
- Updated the `sample.html` template to use `splitlines()` for proper line-by-line display
Tested the solution by viewing fuzz targets with varying code complexity:
- Simple fuzz targets with minimal code
- Complex targets with many lines and various indentation levels
- Code with extra-long lines that require horizontal scrolling
Fixes #335
https://github.com/user-attachments/assets/70d4a1ea-8e6f-41c9-a9a1-e67cb0bd862d
_Note: The demo uses static sample example code and doesn't contain any sensitive data._

Report: Add line numbers to fuzz targets

---

benchmark-sets/comparison/expat.yaml
experiment/oss_fuzz_checkout.py

Unify the way to use cached images when building the fuzz targets in agents and Execution stage.

Unify cached images

---

agent/enhancer.py
agent/prototyper.py
llm_toolkit/prompt_builder.py
prompts/agent/enhancer-priming.txt

In enhancer agent, teach LLM to write fuzz targets and build scripts in the same way as prototyper.
Currently it writes them with \`\`\`

Fixing and customizing the enhancer prompt

---

.gitignore

This PR adds `.vscode`, which contains configurations such as a `launch.json` for [debugging code with breakpoints on VSCode/Cursor](https://code.visualstudio.com/docs/editor/debugging), to `.gitignore` so that these local configs are not included as part of the git working tree.

Add `.vscode` to `.gitignore`

---

run_all_experiments.py

This is needed when running analysis by way of e.g. https://github.com/google/oss-fuzz-gen/tree/main/scripts/run-new-oss-fuzz-project

enable coverage analysis for projects with no coverage

---

logger.py

This is causing issues where we have multiple harnesses in a single *.fuzz_target

logger: make sure to overwrite harness instead of appending

---

experimental/c-cpp/manager.py

Ref: https://github.com/ossf/fuzz-introspector/pull/2120
Will make it faster to generate empty builds.

c-cpp: disable light when testing introspector builds

---

ci/ci_trial_build.py

fix: correct args order in CI trial build script

---

report/common.py
run_all_experiments.py

These changes are based on the discussion in #859.
- Removed environment variable for storing `num_samples` from `run_all_experiments.py`
- Added trial count directly to `report.json` using existing `add_to_json_report` function
- Modified `_get_expected_trials_count()` to first check `report.json` for `num_samples`

Store trial count in report.json instead of environment variable

---

experiment/oss_fuzz_checkout.py

If WORKDIR is relative, this causes it to be set to an incorrect value because it's already set in the parent image (e.g. /src/proj/proj instead of /src/proj).
Related: https://github.com/google/oss-fuzz/pull/13151 which needs to get merged and deployed first.

Don't keep WORKDIR when writing cache image.

---

experiment/oss_fuzz_checkout.py

Sometimes it's useful to use a virtual environment that is not used in the given path. If the VIRTUAL_ENV environment is set, then we can assume we are in a correct virtual environment.

oss_fuzz_checkout: relax constraints on venv check

---

experimental/build_generator/runner.py
scripts/run-new-oss-fuzz-project/run-project.sh

Makes it possible to run auto harness generation on generated builds as part of the same command
```sh
MODEL=gpt-4o python3 -m experimental.build_generator.runner \
-of oss-fuzz/ -i targets2.txt -o generated-3 --generate-harness
```
ref: https://github.com/google/oss-fuzz-gen/issues/911

build-generator: add option for running OFG generation

---

report/templates/crash.json

This PR fixes JSON format errors in crash reports due to improper escaping or were missing quotes entirely, causing parsing errors referenced in issue.
fixes: #903 
* Added proper quotes around template expressions
* Added proper escaping for double quotes with `\"`
* Added proper formatting for newlines as `\n`
Before:
```json
{
"samples": [
{
"coverage_report": "#",
"stacktrace": "/stacktrace",
"target_binary": "/target_binary",
"reproducer": "/artifacts",
"run_log": "run.log",
"source_code": ,
"model": "claude-3-opus-20240229"
}
]
}
```
After:
```json
{
"samples": [
{
"coverage_report": "#",
"stacktrace": "SIGSEGV\ncrash at 0x004a3f21\n#0 0x004a3f21 in function()",
"target_binary": "/target_binary",
"reproducer": "/artifacts",
"run_log": "run.log",
"source_code": "#include …
```

Add proper JSON escaping in crash report templates

---

report/common.py
report/templates/crash.json
report/web.py

This PR addresses the issue of missing source code by adding enhanced logging and improving error handling in the `get_benchmark_final_target_code()` method. Previously, silent failures could occur, making it difficult to diagnose the root cause of missing source code.
- **Enhanced Logging**: Logs are added to track when the `sample_id` is invalid or the source code is missing.  
- **Error Handling**: Ensures that malformed or empty `sample_id` values are handled gracefully and logged appropriately.  
- **Return Null for Missing Source Code**: In case of an error, the function explicitly returns `None` rather than an empty string for clarity in JSON outputs.  
#908
It may also refer to https://github.com/google/oss-fuzz-gen/issues/625
- Improved **debuggability** by making it easier to …

Fix Logging and Error Handling for get_benchmark_final_target_code

---

experiment/oss_fuzz_checkout.py

This reverts commit aaaf0f8ef1e5202d0e8190089a6d7219b9ce82ac to identify root cause of recent bugs that affects all experiments.

Revert "oss_fuzz_checkout: relax constraints on venv check (#916)"

---

experimental/end_to_end/cli.py

Removes dependency on https://github.com/google/oss-fuzz-gen/tree/main/scripts/run-new-oss-fuzz-project so that we do it all in python itself now.
There's still calls to various `subprocess.check_call`. Some of these are tricky to get away from, since not all dependencies are build like libraries as such. Will keep these for now.

end-to-end: remove dependency on scripts /run-new-oss-fuzz-project/

---

experiment/evaluator.py
logger.py
pipeline.py
report/common.py
results.py
run_one_experiment.py

1. Add a field to result representing a trial's status (finished or not).
2. Include `finished/all` ratio in report index page.

Refine the status in reports

---

prompts/agent/prototyper-priming.c.txt
prompts/agent/prototyper-priming.cpp.txt
prompts/agent/prototyper-priming.txt

- Updated terminology in prototyper priming templates by replacing "minimum fuzz target" with "compilable fuzz target" in:
- `prompts/agent/prototyper-priming.txt`
- `prompts/agent/prototyper-priming.c.txt`
- `prompts/agent/prototyper-priming.cpp.txt`
The inclusion of "minimum" in the initial set of prompts might confuse LLMs into believing that they should reduce the fuzz target code size at the expense of functionality. This change clarifies that the goal is to arrive at a working fuzz target that successfully compiles, and not a minimum one.
Fixes #929

Update prompts to clarify fuzz target requirements

---

.github/workflows/osv-scanner-pr.yml

--skip-git is not used anymore:
https://github.com/google/osv-scanner/blob/main/docs/migration-guide.md

ci: osv-scanner: fix wrong cli argument

---

report/templates/index.html

Seeing some rare failures caused by missing keys in dictionary:
```python
ERROR 2025-04-02T10:58:43.024642067Z Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/experiment/report/web.py", line 331, in <module> main() File "/experiment/report/web.py", line 312, in main generate_report(args) File "/experiment/report/web.py", line 260, in generate_report gr.generate() File "/experiment/report/web.py", line 169, in generate self._write_index_html(benchmarks, accumulated_results, time_results, File "/experiment/report/web.py", line 194, in _write_index_html rendered = self._jinja.render(
ERROR 2025-04-02T10:58:43.024864987Z ^^^^^^^^^^^^^^^^^^^
ERROR 2025-04-02T10:58:43.024869177Z File …
```

Safer dictionary access on report index page

---

experimental/end_to_end/cli.py

To create complete OSS-Fuzz projects with multiple harnesses.

end-to-end: add simple post-harness-gen merging

---

experiment/oss_fuzz_checkout.py

This makes it easier to run OFG with projects not yet in OSS-Fuzz

oss-fuzz-checkout: enable syncing with user-provided folder

---

experimental/end_to_end/cli.py

Makes it easier to run cloud experiments after a run.

end-to-end: create data-dirs after build generation

---

agent/one_prompt_enhancer.py
agent/one_prompt_prototyper.py

The logs when shown in the report a not formatted well for openai models, as they are dictionaries not plaintext. We want only the plaintext in the logs.

agent: one-prompt*: use gettext for logs

---

experimental/end_to_end/cli.py

We need to delete the .gitignore because the data files should be uploaded to the git PRs. We need to harden the copying in case some projects were killed externally. These behaviours were observed in the most recent large-scale e2e run.

e2e: harden data copying and delete .gitignore from fi

---

experimental/build_generator/templates.py

This is to improve performance based on observations from https://github.com/google/oss-fuzz-gen/pull/989

build-generator: disable fi light during generation

---

Dockerfile

This issue aims to refactor the current Dockerfile to use a multistage build approach. The motivation for this change is to:
1. Reduce final image size by excluding unnecessary build-time dependencies (e.g., gcc, libpython3-dev, etc.)
2. Enhance maintainability by clearly separating build and runtime concerns
```
Size of the current docker image: 3.82GB
Size of the docker image after multi-stage build: 1.06GB
```
Closes #990

Dockerfile enhancement: multistage build

---

llm_toolkit/prompt_builder.py
stage/analysis_stage.py

Following https://github.com/google/oss-fuzz-gen/pull/928 the analysis stage tries to get a a coverage agent https://github.com/google/oss-fuzz-gen/blob/d12ae0e2a9a51dcbc1e2655288b059954a25dc48/stage/analysis_stage.py#L38 and throws a RuntimeError if it does not exist: https://github.com/google/oss-fuzz-gen/blob/d12ae0e2a9a51dcbc1e2655288b059954a25dc48/stage/base_stage.py#L55
But only the agent approach has a CoverageAnalyzer: https://github.com/google/oss-fuzz-gen/blob/d12ae0e2a9a51dcbc1e2655288b059954a25dc48/run_one_experiment.py#L256
This fixes it by enabling so an error is not thrown if there's no coverage analyzer agent in the analysis stage. Ultimately I assume one of the aims of the architecture around the pipeline/modularised agent is to support plug-and-play style (many agents, …

one-prompt: fix bug for missing coverage agent

---

results.py

We're running into issues in the cloud build when dill deserialization fails, because https://github.com/google/oss-fuzz-gen/blob/d12ae0e2a9a51dcbc1e2655288b059954a25dc48/common/cloud_builder.py#L422 may return a Result object, which gets called from https://github.com/google/oss-fuzz-gen/blob/d12ae0e2a9a51dcbc1e2655288b059954a25dc48/stage/base_stage.py#L62-L63 which get's called from https://github.com/google/oss-fuzz-gen/blob/d12ae0e2a9a51dcbc1e2655288b059954a25dc48/stage/analysis_stage.py#L39 and the pipeline uses the success field: https://github.com/google/oss-fuzz-gen/blob/d12ae0e2a9a51dcbc1e2655288b059954a25dc48/pipeline.py#L123-L127 but the base Result class does not have a success field: https://github.com/google/oss-fuzz-gen/blob/d12ae0e2a9a51dcbc1e2655288b059954a25dc48/results.p …

results: add success field to base class

---

experimental/build_generator/build_script_generator.py
experimental/build_generator/file_utils.py
experimental/build_generator/llm_agent.py
experimental/build_generator/manager.py
experimental/build_generator/runner.py
experimental/build_generator/templates.py

This PR initialis the LLM approach for automatic build script generation of C/C++ projects. This is done by adding a separate path for the new LLM agent. Adding an extra flag --agent could trigger the new LLM agent flow for automatic build script generation.

build_generation: Add LLM approach

---

experimental/build_generator/runner.py
experimental/build_generator/templates.py

https://github.com/google/oss-fuzz-gen/pull/979 caused issues when using `oss-fuzz-generator` from the installed package, because `requirements.txt` is not found in the package. Fixing this by avoiding to copy it in, and just install the library we need.

build-generator: re-enable e2e after installation

---

experimental/build_generator/build_script_generator.py
experimental/build_generator/manager.py

Sometimes we don't want to link all static libs produced. We shuold test combinations of each.
Also add further makefile adjustments and adds `--no-whole-archive` after linking in the relevant found libraries. This is to avoid linking in whole std libraries, which can cause issues and is bad practice.

build-generator: support linking against multiple libs

---

experimental/build_generator/llm_agent.py
experimental/build_generator/runner.py
experimental/build_generator/templates.py

Following #979, it was observed that the container tools execute the generated build script within the Docker image using a single command. If the **final** command in that script succeeds, the Docker execution will return an exit code of `0`—even if earlier commands have failed. This leads to false positives in interpreting the build result.
This PR addresses the issue by prepending `set -e` to the command sequence passed to the container tool. This ensures the script exits immediately upon any command failure, preserving the non-zero exit code to correctly indicate build script failures.
Additionally, this PR improves parts of the prompt templates and refines the retry-wait logic, resulting in more reliable LLM-driven build script generation.

build_generation: Fix false positive result

---

experimental/build_generator/runner.py

This PR fixes the agent approach of the build_generation to avoid copying unused files into the oss-fuzz directory for the generated projects.

build_generation: Avoid redundant copying for agent approach

---

experimental/build_generator/llm_agent.py
experimental/build_generator/manager.py
experimental/build_generator/runner.py
experimental/build_generator/templates.py

This PR add a new build_generation agent to auto discovery the target project in a docker image and create a build script after gathered enough information.

build_generation: Add auto discovery agent

---

experimental/build_generator/llm_agent.py
experimental/build_generator/runner.py
experimental/build_generator/templates.py

This PR addresses two issues that impact the success rate of the Auto Discovery Build Generation Agent:
1. Occasionally, the LLM returns invalid results with incorrect tags for parsing. This PR introduces a new prompt to explain the situation to the LLM and instruct it to correct the response.  
2. The LLM model was previously instantiated only once for all projects and trials, resulting in a bug where chat history from previous projects was incorrectly preserved and influenced subsequent LLM processes. This PR resolves the issue by reinitialising the LLM model for each project trial.

build_generation: Fix invalid response handling and llm model handling

---

experimental/build_generator/llm_agent.py

I observed several cases where a response from the LLMs are in the format:
```
The `Makefile` provides several targets, primarily for testing and examples. There are no explicit targets for building a static library or object files, but we can compile `jsmn.c` directly to create the necessary object files or a static library for linking with our fuzzer.
Here's the plan:
1. Compile `jsmn.c` to an object file.
2. Archive the object file into a static library.
3. Compile the fuzzing harness with the static library.
Let's proceed with generating the build script and updating the fuzzing harness.
```bash
<bash>
if [ -z "${CFLAGS:-}" ]; then
CFLAGS="-I$SRC/jsmn"
else
CFLAGS="$CFLAGS -I$SRC/jsmn"
fi
$CC $CFLAGS -c $SRC/jsmn/jsmn.c -o jsmn.o
llvm-ar rcs libjsmn.a jsmn.o
$CC $CFLAGS …

build-generator: make sure we only parse a single build script

---

agent/base_agent.py

get() provides json formatted output for OpenAI prompts, which is tricky to read in the logs. Formatting with gettext makes following the logs much more intuitive.
This is similar in nature to https://github.com/google/oss-fuzz-gen/pull/976

base_agent: use gettext when logging

---

experimental/build_generator/llm_agent.py

I found 60 seconds to be quite excessive and makes experimentation really slow. I did not find any problems with a reduced sleep time.

build_generator: llm_agent: reduce sleep time

---

experimental/build_generator/runner.py

Otherwise, oss_fuzz_checkout will default to oss-fuzz as the relevant dir, which does not match the oss_fuzz_base if set:
https://github.com/google/oss-fuzz-gen/blob/165fdc1334b6e37b55576763d3dc427f854dfefe/experiment/oss_fuzz_checkout.py#L426-L434
This is called by the container tool used by the agent.
This PR fixes so oss_fuzz_checkout uses the appropriate folder.

experimental: build_generator: set OSS_FUZZ_DIR in agent workflow

---

experimental/build_generator/llm_agent.py
experimental/build_generator/runner.py
experimental/build_generator/templates.py

This PR addresses several issues related to LLM templates and enhances the validation of generated build results to ensure they are correct and reliable.
The following changes have been made:
1. Removed the XML code wrapper from templates to prevent confusion for the LLM.
2. Added a test to verify that the compiled fuzzing harness binary is correctly placed in the `$OUT` directory after a successful compilation.
3. Integrated a Fuzz-Introspector check for successfully built projects.
4. Removed a redundant trial in runner.py, which unnecessarily retried the entire process, despite retry logic already being handled within the LLM agents; this change helps to speed up the overall process.
5. Fixed a bug in bash command processing where commands from the LLM were incorrectly treated as a …

build_generation: Fix template and add validation

---

experimental/build_generator/constants.py
experimental/build_generator/llm_agent.py
experimental/build_generator/runner.py

As of #1017, the prompt truncation process has been implemented directly in the OpenAI LLM models. This makes the additional truncation in the build_generator LLM agent unnecessary and potentially confusing. This PR removes the redundant second truncation from the LLM agent.

build_generator: Remove unnecessary truncation

---

experimental/build_generator/runner.py

This PR fixes a bug where only one working environment was being used for all projects, causing files from previous projects to be copied incorrectly. For example, if the last project was a C project and the current one is a C++ project, an old file (empty-fuzzer.c) was copied over. This file wasn’t overwritten and caused build errors since it wasn't compatible with the new project. The fix ensures a fresh working environment is created for each project, preventing this issue.

build_generator: Fix bug for working directory preperation

---

experimental/build_generator/llm_agent.py
experimental/build_generator/templates.py

This PR includes the following changes:
1. Added missing Fuzz-Introspector environment variable to reduce redundant output in the final results.
2. Change the agent flow to allow LLM returns to the interaction process if needed.
3. Updated the build prompt with several fixes:
- Added strict constraints to avoid guessing and encourage returning to the interaction process.
- Clarified build system detection and emphasized that listed examples are not exhaustive.
- Tightened rules on compiler flag use and header inclusion.
- Prohibited use of macros and type defines unless absolutely necessary.
- Added a "Common Mistakes to Avoid" section to summarise key restrictions.

build_generation: Refine the guideline for build script generation

---

experimental/build_generator/runner.py

This PR fixes a bug in the build generation where some projects contain capital letters, which are not permitted in OSS-Fuzz project names.

build_generation: Avoid upper case project name

---

experimental/build_generator/templates.py

This PR strengthens the build script generation prompt with the following improvements:
1) Enforces use of `$SRC` in include paths to ensure correct header resolution.
2) Requires use of `apt-get` to install dependencies before falling back to manual builds of missing dependencies.
3) Adds explicit handling for Android.bp (Soong) projects and AOSP build assumptions.
4) Prohibits manual compilation when a valid build system (e.g., Makefile) exists.
5) Adds support for minimal compatibility shims (e.g., for BSD macros) when needed.
6) Improves discovery strategy by including README/INSTALL parsing suggestion.
7) Tightens rules around excluding tests and use of `make -C` and flags.

build_generation: Fix prompt for strict constraint and more guideline

---

experiment/oss_fuzz_checkout.py

Logging that we'll be using caching should only happen if we will actually use caching.

oss_fuzz_checkout: fix logging location

---

experimental/build_generator/runner.py
experimental/end_to_end/cli.py

Previously issues would happen if repositories ended with '/'. This fixes it so we dont run into issues by removing trailing '/'.

e2e: harden repository recognition and add default out

---

report/templates/index.html

This PR fixes an error in the oss-fuzz-gen's experiment result page where true positive crashes are classified as false positives, and vice versa.
In report/templates/benchmark.html, crashes are designated as True vulnerabilities if `sample.result.crashes and **not** sample.result.is_semantic_error`.
However, in report/templates/index.html, the reverse occurs. Crashes were previously designated as True positives if `bug_sample.sample.result.is_semantic_error`. This PR fixes this discrepancy.

Fix error in true/false positive crash designation on the experiment result page

---

experimental/end_to_end/cli.py

This should not be used for end-to-end projects, where we expect the targets to be non-OSS-Fuzz projects

end-to-end: disable caching

---

data_prep/introspector.py

We shuold let the FI API make the decision here. This is to enable benchmark generation for some cases where it was unintuitive why there were no targets.

introspector: avoid discarding unreached targets

---

tool/base_tool.py

This is needed when running `oss-fuzz-generator` in locations not in OFG root.

base-tool: make accessing .txt files independent of cwd

---

data_prep/introspector.py
experimental/end_to_end/cli.py
run_all_experiments.py

This is a useful feature for both doing targeted harness generation as it allows us to bypass oracles and go for a function we, for some reason, find interesting. This is also very useful for development purposes.

end-to-end: enable targeting specific function

---

experimental/build_fixer/build_fix.py

otherwise we end up declaring everything a success erroneously.

build-fixer: break without changing exit condition on max rounds

---

experimental/build_fixer/build_fix.py

Otherwise we risk infinite loops, which does happen.

build-fixer: always increment loop counter

---

agent/one_prompt_prototyper.py

Sometimes the compile_log data in build_result is truncated due to excessive stdout and stderr output from the test build. This can result in missing error messages and cause the error extraction logic to fail, preventing any error messages from being passed to the LLM for code fixing.
This PR resolves the issue by also using the full stderr stored in build_result.compile_error to extract error messages, and introduces deduplication logic to avoid sending repeated messages to the LLM.

one_prompt_prototyper: Fix error extraction

---

tool/fuzz_introspector_tool.py

This PR fixes a bug introduced in #1092 where `func["debug_summary"]["name"]` could be `None` or an empty string even if the keys exist.

Fix bug in FI None value handling

---

llm_toolkit/prompt_builder.py

This PR fixes an incorrect check where, if either error_desc or errors is empty, the entire error message is skipped. It also improves the handling of error messages to ensure that at least one is included for the LLM to process, even when the token limit is reached.

prompt: Fix error message handling

---

common/cloud_builder.py

This PR fixes experiment failures caused by using excessive storage.
The problem was caused by temporary files being created but not getting deleted.

Fix use of excessive storage during experiments

---

llm_toolkit/prompt_builder.py

This PR fixes #1052 by ensuring that detailed build error messages are retained when generating fixer prompts.
Changes:
- Prevent errors from being cleared if error_desc is empty but errors has content.
- Default error_desc to an empty string if None.
- Default errors to an empty list if None.
This avoids the “Unexpected empty error message” warning.

Handle empty error description and errors in DefaultTemplateBuilder

---

data_prep/introspector.py
data_prep/project_context/context_introspector.py
prompts/template_xml/context.txt

This PR refines the xrefs test context to more precisely include the line of the target function call, along with the lines where its parameters are defined and initialised, to provide more accurate and minimal information for prompt creation.

context: Fix xref api calls

---

agent/base_agent.py
agent/coverage_analyzer.py
agent/crash_analyzer.py
agent/function_analyzer.py
agent/prototyper.py
experimental/build_generator/llm_agent.py

This PR does the following:
- Fixes the bug where CrashAnalyzer returns prematurely after receiving an invalid LLM response.
- Modifies the function for handling invalid LLM Responses (_container_handle_invalid_tool_usage) so it can handle multiple tools. CrashAnalyzer requires this.
- Updates callers of _container_handle_invalid_tool_usage so they pass a list of tools, instead of a tool object.

Update CrashAnalyzer to Handle Invalid LLM Responses

---

report/docker_run.py
report/export.py
report/templates/base.html
report/upload_report.sh
report/web.py

This PR adds a basic CSV export functionality for the report. 
Each row in the CSV is a trial/sample. The headers are:
- `Project`: Human-readable project name
- `Function Signature`: Human-readable function signature
- `Sample`: Hyperlink to the trial/sample page in the report
- `Crash Type`: Whether the sample is a true or false positive crash
- `Compiles`
- `Crashes`
- `Coverage`
- `Line Coverage Diff`
- `Reproducer Path`
To trigger CSV export, run experiments with an added `-csv` or `--with-csv` flag. The generated CSV can then be accessed via the report itself (by clicking on the top-left 'Export' button), or found at the root of the results directory as `crashes.csv`.

Add CSV export for the report

---

prompts/tool/gdb_tool.txt

This pr is used to optimize the gdb prompt. The language is more refined and unified, and the structure is clearer. 
In particular, In GDB, do not use shell-style redirection like:
```run < {AFTIFACT_PATH}```
This won't work because GDB is not a shell. I have seen too many these cases, LLM model like GPT-4o also makes this mistake.
Also, avoid using:
```run -- {AFTIFACT_PATH}```
unless the fuzz driver explicitly expects that pattern. Relevant case: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2025-07-01-1133-pamusuo-comparison/sample/output-igraph-igraph_sparsemat_arpack_rssolve/03.html#:~:text=54%3A58%20%5BTrial%20ID%3A%2003%5D%20INFO%20%5Bbase_agent.-,chat_llm,-%3A96%5D%3A
Furthermore, while ```run {AFTIFACT_PATH}``` seems correct, it may execute the testcase multiple times, …

Optimize GDB prompt in CrashAnalyzer

---

report/parse_logs.py
report/templates/base.html
report/templates/index/index.html
report/templates/index/index.js
report/templates/sample/sample.html
report/web.py

This PR adds step parsing for each agent section to transform the raw content at each step into a more human-readable format, with collapsible subsections containing a text preview of the chat prompt/response (first 50 words).

Add step parsing for each agent section
