google/oss-fuzz-gen

.github/helper/presubmit
Print out the filenames and line numbers changed, so that people can read them from CI error.
=> More informative linting

USAGE.md
=> Fix command typo

data_prep/project_context/context_retriever.py
Add anon client to download ASTs from gcs bucket.
Also some path changes (more usage of os.path).
Fixes #21
=> Add anon client

.github/workflows/push-to-gcr.yml
=> Add a github action to automatically push to gcr from HEAD

data_prep/project_context/context_retriever.py, run_one_experiment.py
context retriever changes to support new benchmark format
=> Context benchmark changes

report/web.py
Addressing https://github.com/google/oss-fuzz-gen/pull/73#discussion_r1483395808
=> Simplify code

experiment/builder_runner.py
=> improve pre-build target function checking

llm_toolkit/prompt_builder.py
There was a confusion between the priming text and the priming prompt. It is not a problem for text prompts where the role is ignored, but for structured prompts (OpenAI), we got into a state where the structured prompt was a nested structure:
```json
{
"role": "system",
"content": [
{
"role": "system",
"content": "Given the following C++ program and its build error message, fix the code to achieve the original functionality.\n\nIf a function is missing, fix it by including the related libraries.\n\nIf the error contains \"undefined reference to\", this means one or more of the header <code>#include</code> directives need to be wrapped with <code>extern \"C\" {}</code> for the object linking to succeed. You must fix this by rewriting the relevant <code>#include</code> and wrapping it with …
```
=> Fix priming for fixing on OpenAI models.

llm_toolkit/models.py
They also have increased context windows per
https://cloud.google.com/vertex-ai/docs/generative-ai/learn/models
=> Update Gemini model name.

experiment/evaluator.py
Continue from #111 to fix #115.
Some `benchmark.id` has a trailing `_`, which caused [this error](https://github.com/google/oss-fuzz-gen/issues/115#issuecomment-1953133383) when concat with `-{sample_id}`.
This PR fixes this error and cleans up code by moving all steps to fix the docker tag after appending `-{sample_id}`.
=> Fix docker image tag by removing trailing special chars in benchmark id

helper/result_string_search.py
=> add helper script to search string in result

experiment/evaluator.py, experiment/textcov.py
Our current line coverage measurement includes the lines from the fuzz target.
It's fairer to measure the lines from the project only, not the fuzz target, so that covering more lines in the fuzz target will not increase the code coverage.
A PoE:
[`cppitertools-Iterator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > &> zero_length_end(std::__1::allocator<char> >)`](https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-03-02-weekly-all/benchmark/output-cppitertools-_zn4iter4impl10combinatorirnst3__112basic_stringicns2_11char_traitsiceens2_9allocatoriceeeee8iterato)
=> Exclude fuzz target code from coverage measurement

data_prep/README.md, data_prep/introspector.py
Use argparse for introspector's module. This fixes a todo and will also make it easier to add more feature to the introspector module.
=> data_prep: use argparse for introspector

helper/result_string_search.py
=> Skip non dir entries while looping through results folder

prompts/template_xml/fixer_priming.txt, prompts/template_xml/fixer_problem.txt
Slight improvement on coverage diff on multiple projects
#44 
Also tries to address #126
=> Improve code fixing prompt

experiment/builder_runner.py
[#151 comment](https://github.com/google/oss-fuzz-gen/pull/151#issuecomment-1992869816)
=> Retry on broken pipe and refactor error handling

README.md
- Fix count
- Add clarification on why these bugs are interesting.
=> Clarify previously discovered bugs.

README.md
Also add brief descriptions to existing ones for consistency.
=> Add one more undisclosed vuln.

README.md
Add a new column to separate bugs from project names.
Add OSS-Fuzz links to projects.
=> Beautify Trophy List

README.md
zstd bug fix has been merged and released upstream.
=> Disclose zstd bug

llm_toolkit/code_fixer.py, llm_toolkit/models.py, run_all_experiments.py, run_one_experiment.py
- ensure it is getting k-time LLM inference results instead of top-k results for one time LLM inference
- changed number of samples to 1 and number of repeat to a larger value 6
- passed the format check by running `.github/helper/presubmit`
=> add number of repeat

experiment/oss_fuzz_checkout.py
Supersedes: https://github.com/google/oss-fuzz-gen/pull/193
=> oss_fuzz_checkout: avoid breaking on permission errors

experiment/evaluator.py
Fix the bug where the build succ rate is not correctly collected when build fails.
=> Fix missing build results in case of code fixing failure

experiment/evaluator.py, experiment/fuzz_target_error.py, experiment/workdir.py, report/web.py
This contains all commits cherry-picked from #209 , thanks for your instruction~
=> Cherry pick for "Minor updates by bug fixes and feature improvements"

experiment/builder_runner.py, experiment/workdir.py
=> Download jcc err.log

experiment/builder_runner.py
This fixes the bugs found in the [report](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-04-23-222-dg-comparison/benchmark/output-flex-main2/index.html):
- 03 & 10 -> add TODO to include oom/slow cases into the semantic check result & fix
- 07 -> add more string patterns `LIBFUZZER_LOG_STACK_FRAME_LLVM2` to identify whether the file path is of target project or out of project 
- no coverage increase case should return `False` in `crashes`
=> fix several bugs & add todo for handling oom/slow cases

experiment/builder_runner.py
Similar to #212 but for local experiments.
=> Retrieve jcc err.log in local experiments

experiment/evaluator.py
- fixes the error mentioned in #222 
- refine logs
=> Fix incorrectly returned is_semantic_err

ci/Dockerfile, ci/README.md, ci/__init__.py, ci/ci_trial_build.py, ci/cloudbuild.yaml, ci/k8s/pr-exp.yaml, ci/request_pr_exp.py, ci/requirements.txt
=> Set up gcbrun for running experiments.

llm_toolkit/models.py
=> Add support for Gemini 1.5.

experimental/c-cpp/manager.py
This commit improves the logic by:
- Identifying language of target project, to make language specific
prompts
- Adds context to the prompts based on cross-references, source code and
extended typing
- Adds two new prompts for C
- Adds an addition harness run for each auto-gen harness with
`detect_leaks=0`. This is to get idea of how well a harness performs
in the event it runs into a leak fast.
- Saves the introspector reports used per analysis. This is important
for development purposes to make it easy to track what the prompts
used.
- Saves the prompts generated per auto-gen harness.
=> experimental: extend and improve various places

CITATION.cff, README.md
Show people how to easily use our `CITATION.cff` to generate the citation file they need (e.g., `Bibtex`).
=> More informative instruction to generate citation files

report/web.py
Add additional file extensions for finding targets.
=> Fix report generation for Java and Python.

ci/ci_trial_build.py
I often found myself typing [the incorrect command](https://github.com/google/oss-fuzz-gen/pull/279#issuecomment-2118807874).
Hope this can help.
=> Simplify PR exp command

requirements.in, requirements.txt
Some experiment trials failed due to [the failure to initialize the vertex AI model with the given location](https://pantheon.corp.google.com/logs/query;cursorTimestamp=2024-05-20T21:40:30.302955392Z;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22oss-fuzz%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.cluster_name%3D%22llm-experiment-large%22%0Aresource.labels.namespace_name%3D%22default%22%0Alabels.k8s-pod%2Fbatch_kubernetes_io%2Fcontroller-uid%3D%226b65ab48-fbd1-4f95-968e-8acf8c36f40c%22%20severity%3E%3DWARNING%0A%0A%0A%0A-textPayload%3D~%22Cannot%20find%20cloud%20run%20log%22%0A-textPayload%3D~%22Multiple%20substring%20matches%22%0A-textPayload%3D~%22Failed%20to%20parse%20error%20message%22%0A-textPayload%3D~%22Unexpected%20empty%20error …
=> Update `aiplatform` and related pacakges

requirements.in, requirements.txt
Related: https://github.com/google/oss-fuzz-gen/actions/runs/9175918219/job/25229988627
=> Update vulnerable `requests` package

.github/workflows/osv-scanner.yml
Address this:
https://github.com/google/oss-fuzz-gen/actions/runs/9474289246/workflow
=> Grant read action permission to osv-scanner

report/upload_report.sh, report/web.py, requirements.in, requirements.txt
This is the first step towards making reports directly read/write to both local disk and GCS.
=> Refactor report generation tool

run_one_experiment.py
Ref:
https://github.com/google/oss-fuzz-gen/pull/310#issuecomment-2160313471
=> run_one_experiment: clarify warning

experimental/c-cpp/build_generator.py, experimental/c-cpp/manager.py, experimental/c-cpp/runner.py
It's desirable to isolate the use of a subset of all the builders to speed up development time
=> experimental: make it possible to select build rules to use

experimental/manual/oss_fuzz_vuln_prompt.py
E.g. try with (for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69527): 
python -m experimental.manual.oss_fuzz_vuln_prompt --repo_url=https://github.com/libical/libical --regression_range=dafb8b6c5224df23e2d0dde8df56175dcaa99792:2026582a94915dc3988b40ab222a4d975fd0f10c --crash_revision=2026582A94915DC3988B40AB222A4D975FD0F10C --crash_stacktrace=stacktrace.txt > prompt.txt
python -m experimental.manual.prompter -p prompt.txt -l vertex_ai_gemini-1-5
=> Generate a prompt to identify and remediate the security vulnerability.

llm_toolkit/prompt_builder.py
This PR fixes a bug in JVM full class name handling process for inner class.
=> JVM: Fix bug on inner class name handling

experimental/c-cpp/manager.py, experimental/c-cpp/runner.py
Makes it easier to focus during development and make experiments targeted
=> experimental: make it possible to pick harness generation heuristics

data_prep/introspector.py
Avoid confusing name
Ref: https://github.com/google/oss-fuzz-gen/pull/431#discussion_r1665698977
=> introspector: rename JVM public candidate oracle

report/common.py, report/templates/index.html, report/web.py
This makes it a lot easier to track progress and also spot regressions.
=> report: Add macro insights to HTML report

data_prep/parse_training_data.py
Training data generator crashes in recent experiments because we added triage directories (e.g., [03-triage/](https://pantheon.corp.google.com/storage/browser/oss-fuzz-gcb-experiment-run-logs/Result-reports/scheduled/2024-07-06-weekly-all/results/output-eigen-_zn5eigen9transposeins_5blockins_6matrixinst3__17complexideelin1elin1eli0elin1elin1eeelin1eli1elb1eeee6resi/fixed_targets/03-triage?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&e=-13802955&mods=logs_tg_prod&project=oss-fuzz)) and breaks this line:
https://github.com/google/oss-fuzz-gen/blob/main/data_prep/parse_training_data.py#L83
This PR fixes it with a more fine-grained regex to identify code fixing directories (e.g., [03-F5/](https://pantheon.corp.google.com/storage/browser/oss-fuzz-gcb-experiment-run-logs/R …
=> Fix training data generator

experiment/oss_fuzz_checkout.py
Ref: https://github.com/google/oss-fuzz-gen/pull/456/files#r1669405244
=> experiment: fix readability of conditional

llm_toolkit/prompt_builder.py
This PR fixes the generic type description handling for unspecified generic types.
=> JVM: Fix generic type handling

llm_toolkit/prompt_builder.py, prompts/template_xml/jvm_specific_data_filler.txt
This PR fixes the random method description of primitive types and simple types.
=> JVM: Fix simple object discovery

report/templates/index.html, report/web.py, run_all_experiments.py
This is useful for tracking performance.
=> add timestamps to out and web

experimental/c-cpp/runner.py
otherwise the storage is getting eaten too fast
=> experimental: delete docker images after runs

experiment/textcov.py
=> JVM: Fix coverage calculation for JVM project

data_prep/introspector.py, run_all_experiments.py, run_one_experiment.py
1) Fix logging format issues
2) Fix unused import
3) Fix use of double quotes
=> fix CI warnings across several files

experimental/c-cpp/post-process.py
Also adds argparse logic.
This is working towards end-to-end combination with core OFG.
Ref: https://github.com/google/oss-fuzz-gen/issues/450
Signed-off-by: David Korczynski <david@adalogics.com>
=> experimental: add utility for extracting top projects

experimental/c-cpp/post-process.py
Ref: https://github.com/google/oss-fuzz-gen/issues/450
=> experimental: add logic to copy top projects to dst

experiment/evaluator.py, report/common.py, report/templates/index.html, report/web.py, run_all_experiments.py, run_one_experiment.py
=> Add project summary to console output and web report 

experimental/c-cpp/constants.py, experimental/c-cpp/manager.py, experimental/c-cpp/runner.py
Also rename openai to gpt-3.5-turbo
=> experimental: make models into constants

report/aggregate_coverage_diff.py, run_all_experiments.py
Otherwise we're running into issues in the from-scratch e2e. For some reason `KeyError`s only happen some of the times. This fixes it.
=> make reading existing coverage more resilient

README.md, USAGE.md, llm_toolkit/models.py
Based on https://github.com/google/oss-fuzz-gen/pull/545, in which we add support for Azure's GPT model, we updated the logic of `_get_tiktoken_encoding` according to @mihaimaruseac 's advice (https://github.com/google/oss-fuzz-gen/pull/545#discussion_r1723731712).
Specifically, we have updated
1. models.py: Updated `_get_tiktoken_encoding` in the GPT and AzureGPT classes, to reuse it in AzureGPT by calling super method.
2. README.md: showed our support for Azure GPT models.
3. USAGE.md: Updated environment settings and model usage for Azure GPT models.
=> Update the `super` method within GPT, update README and USAGE file

llm_toolkit/models.py, run_all_experiments.py, run_one_experiment.py
1. Cleanup existing code before calling agents:
- more extensible: Pass args instead of each namespace.
- Remove unused parameters and args
1. Implement the basic classes
2. Implement the prototyper agent
=> Agent-enhancement integration (Step 1)

experimental/c-cpp/README.md
Provide correct guide to update combination of from-scratch and OFG core
=> experimental: refine README

experiment/evaluator.py
convertion --> conversion.
Also makes the comments fill out the columns.
=> evaluator: fix minor typo

run_all_experiments.py
Otherwise we may end logging DEBUG statements anyways
=> run_all_experiments: set base logging

report/docker_run.sh, report/trends_report.py
=> Add a tool to generate trends report summary json files after each experiment

README.md
2 older ones were disclosed + add 1 new undisclosed one.
=> Update trophy list

data_prep/introspector.py
no longer relevant as of https://github.com/google/oss-fuzz-gen/pull/578
=> introspector: remove old misleading comment

Dockerfile.cloudbuild-agent, agent/base_agent.py, agent/prototyper.py, ci/k8s/pr-exp.yaml, ci/request_pr_exp.py, common/cloud_builder.py, experiment/workdir.py, logger.py, pipeline.py, report/common.py, report/docker_run.sh, requirements.in, requirements.txt, results.py, run_all_experiments.py, run_one_experiment.py, stage/base_stage.py, stage/writing_stage.py, utils.py
Support cloud experiments:
1. Upload local pickle files for `agent` and `result_history`
2. In cloud build: Install dependecies and run `new_result = agent.execute(result_history)`
3. Download the pickle file of `new_result`
4. Save cloud exp logs
5. If cloud build fails, return a default `new_result` representing build failure.
6. Convert results into `status/**/result.json` for report generation.
7. Upload local OFG repo to cloud build, instead of asking cloud build to pull from repo.
8. Make new `Result` class compatible with report generation.
TODOs:
2. More exception handlings.
3. More intermediate files (local agent dialog)
=> Agent enhancement 3

scripts/run-new-oss-fuzz-project/README.md, scripts/run-new-oss-fuzz-project/run-project.sh, scripts/run-new-oss-fuzz-project/setup.sh
Adds set up that makes it easy to run OFG on any project in a local OSS-Fuzz setup. This is useful during analysis of LLM attributes and also a stepping stone for using OFG while integrating OSS-Fuzz projects.
=> scripts: add set up for running on arbitrary project

USAGE.md
Fixes: https://github.com/google/oss-fuzz-gen/issues/584
=> Usage: fix model naming and expand docs around benchmarks

README.md
I reported this yesterday and didn't add it to the README, and today it was already fixed upstream!
=> Add one more trophy

ci/k8s/pr-exp.yaml, ci/request_pr_exp.py, report/docker_run.sh
Makes it possible to redirect stdout/stderr from experiment run using `-rd`
=> CI: make it possible to redirect stdout/stderr from experiment

data_prep/project_src.py
Fixes: https://github.com/google/oss-fuzz-gen/issues/644
=> project_src: remove unused code

report/templates/index.html, report/web.py
This is to make it easier to traverse bugs in larger experiments
=> report: add bug-specific table

data_prep/introspector.py
This was recently changed. Full API spec in
https://introspector.oss-fuzz.com/api-doc
=> introspector: fix API arg

experiment/builder_runner.py, experiment/oss_fuzz_checkout.py
Also fix the Docker image existence check to properly check remote registries.
=> Support cached images for cloud runner.

README.md
Adding a theory to explain the high code coverage gains (e.g., 98%).
=> Explain unintuitive coverage percentage gain

llm_toolkit/models.py
Discovered in recent experiments.
Will be further examined in later full experiments.
=> Two more retriable errors

experiment/builder_runner.py
It seems that permissions should be granted even without commit.
=> Fix granting permissions only if there is a commit

report/common.py, report/templates/index.html, run_one_experiment.py
This shows which projects cannot benefit from OFG.
=> Show successful benchmarks per project

benchmark-sets/all/neomutt.yaml, benchmark-sets/all/nss.yaml, benchmark-sets/all/perfetto.yaml, benchmark-sets/all/tinyusb.yaml, benchmark-sets/all/wpantund.yaml, benchmark-sets/all/wuffs.yaml, benchmark-sets/all/yoga.yaml
`nss` failed FI build, found the new pair by improving the script in #752:
```bash
#!/usr/bin/env bash
PREFIX="OFG_UNIQUE_PREFIX_"
FILES=$(find /src \
-type f \( -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.cxx' \) \
-not -path '*/aflplusplus/*' \
-not -path '*/fuzztest/*' \
-not -path '*/honggfuzz/*' \
-not -path '*/libfuzzer/*' \
-exec grep -l 'LLVMFuzzerTestOneInput' {} \;)
count=1
for file in $FILES; do
echo "Inserting into $file"
if [[ "$file" == *.c ]]; then
if ! grep -q "build_id_$count" "$file"; then
cat <<EOF >>"$file"
#include <stdio.h>
const char build_id_$count[] __attribute__((used)) = "$PREFIX$file";
__attribute__((constructor))
static void reference_build_id_$count(void) {
fprintf(stderr, "%s\\n", build_id_$count);
}
EOF
fi
else
if ! grep -q "struct …
```
=> Update fuzz target source file path and binary name

experimental/from_scratch/generate.py
got introduced while fixing style issues
=> experimental: from_scratch: fix bug

experimental/from_scratch/README.md, experimental/from_scratch/generate.py
This PR revamp the logic of from_scratch approch to support multiple languages, starting with JVM.
=> from_scratch: Add support for JVM projects

experimental/from_scratch/generate.py
This is supported since
https://github.com/ossf/fuzz-introspector/pull/2063
=> from_scratch: run FI without dumping any files

experimental/from_scratch/generate.py
helper functions are moved to upstream FI
=> from_scratch: simply based on FI upstream

experiment/builder_runner.py, run_all_experiments.py
This PR fixes how rust coverage report is interpreted in build_runner
=> Rust: Fix rust coverage

data_prep/introspector.py, llm_toolkit/prompt_builder.py
This PR remove redundant FI calls.
=> JVM-introspector: Remove redundant FI call

llm_toolkit/models.py
Following https://github.com/google/oss-fuzz-gen/pull/785 we need to use a `ask_llm` in the GPT models. We should propagate this further through but will do that in follow-ups.
=> models: add ask_llm to GPT

prompts/template_xml/jvm_base.txt, prompts/template_xml/jvm_problem.txt
This PR reorganise the base prompt for JVM project in order to clarify the steps for the LLM to perform and generate better fuzzing harness.
=> JVM: Fix base prompt

experimental/from_scratch/generate.py
- use ask_llm instead of query_llm to control output better
- filter output to have proper code
- remove some pylints
=> from-scratch: various improvements

experimental/from_scratch/generate.py
Works better than a long line of CLI args
=> from-scratch: use dedicated commands

report/templates/benchmark.html
Relevant issues #849 and #233.
=> Fix incorrect colour rendering logic

ci/request_pr_exp.py
Fixes lint errors introduced in #845 
cc @DonggeLiu
=> style: fix lint errors

report/templates/benchmark.html, results.py
=> Revive heuristic-based semantic filter

experimental/c-cpp/manager.py
Since we introduced light FI `compile` may return success if light works and core FI fails. In this case, because we simultaneously evaluate the build, we want to ensure we continue if the build succeeds.
=> c-cpp: avoid continuing if core introspector failed

.gitignore
=> add .DS_Store to ignore list

experimental/build_generator/runner.py
Ref: https://github.com/google/oss-fuzz-gen/issues/911
=> build-generator: remove logic no longer used

requirements.in
Address this:
```
0s
Run google/osv-scanner-action/osv-reporter-action@f8[1](https://github.com/google/oss-fuzz-gen/actions/runs/14024801098/job/39261639854#step:6:1)15f2f28022984d4e8070d2f0f85abcf6f3458
/usr/bin/docker run --name ghcriogoogleosvscanneractionv192_9[7](https://github.com/google/oss-fuzz-gen/actions/runs/14024801098/job/39261639854#step:6:8)d538 --label c0daf3 --workdir /github/workspace --rm -e "INPUT_SCAN-ARGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e …
```
=> Address bugs reported by OSV-scanner

experimental/end_to_end/cli.py, scripts/run-new-oss-fuzz-project/run-project.sh
=> end-to-end: enable agentic workflow

experimental/build_generator/build_script_generator.py, experimental/build_generator/constants.py, experimental/build_generator/manager.py, experimental/build_generator/templates.py
This PR adds a new approach for pure Makefile projects. The new approach searches for possibly needed library flag and determine which to add them and also add apt install statements to ensure those package does exist.
=> build_generator: Add new approach with lib flag and packages

requirements.in, requirements.txt
Fixes: https://github.com/google/oss-fuzz-gen/issues/983
=> requirements: bump openai

run_all_experiments.py
In from-scratch runs keyerrors would be observed when accessing the language field. Harden this code to avoid exceptions thrown.
=> run_all_experiments: harden coverage gain logic

USAGE.md, report/web.py
Discussion: https://github.com/google/oss-fuzz-gen/pull/922#issuecomment-2800605474
=> Fix bug where report won't generate without watcher flags

experimental/build_generator/templates.py
adds uuid packages found in a number of projects
=> build-generation: add more packages

experimental/build_generator/llm_agent.py
The container tool used by the Auto Build Discovery Agent, introduced in #1014, kept the Docker session alive until the end of the process. This led to a false positive scenario, where previous test commands and results could affect the outcome of the build script tests.
This PR resolves the issue by refreshing the Docker container session before each test of the build script, thereby avoiding confusion and eliminating false positives.
=> build_Generation: Refresh container before test

experimental/end_to_end/cli.py
Sample way of running this:
`oss-fuzz-generator -i input.txt -w workdir-7 -mr 5 -m gpt-4o -a -o david-out-3`
=> end-to-end: enable agent-based build generation

experimental/build_generator/templates.py, experimental/end_to_end/cli.py
Tested with:
```
oss-fuzz-generator -i input.txt -m gpt-4o -w workdir-6 -a -mr 5 -o gen-6
```
=> improve agent build gen for e2e

experimental/build_generator/templates.py
This PR updates the LLM prompts to enforce stricter build script generation guidelines for the following:
1) Build system order peservation
2) Android.bp dependencies search
3) Avoid forced inclusion of system headers
4) Modifying flags only when necessary
=> build_generation: Fix template for build system order

experimental/end_to_end/cli.py
This allows a more step-wise approach, which is useful for e.g. generate builds in one session, and generating harnesses in other sessions.
=> end-to-end: split cli into multiple commands

experimental/build_generator/runner.py
=> build-generator: harden against exceptions

llm_toolkit/models.py
... To support agents using Gemini 2.5 Pro and Flash.
=> Add chat model for G2.5 flash and pro

experimental/end_to_end/cli.py
--out was buggy and unintuitive for generate-harnesses
This fixes it by removing the argument and improving logging to identify where the merged oss-fuzz projects will be located. Ultimately --out may be a too wide argument in that we have many outputs in the runs, e.g. build scripts, OFG results, merged harnesses, etc. We can probably improve the CLI to make it more intuitive.
=> end-to-end: cli: simplify arguments

agent/base_agent.py
It's a bit confusing we use CHAT for both chat and ask utility functions. This changes so it's clear from the logging when each of them is used.
=> base-agent: adjust logging

experimental/build_fixer/build_fix.py, experimental/build_fixer/templates.py, experimental/end_to_end/cli.py
- Works better with C/CXX
- Improve prompt writings
- Improve OSS-Fuzz build_fuzzers/check_build validation
- Improves code quality
=> build-fixer: improve capabilities

experimental/build_fixer/build_fix.py
=> build-fixer: refactor function execution loop

data_prep/introspector.py
Add new FI API calls for additional information query.
=> data_prep: Add new FI API calls

.github/helper/run_unittests.py, ossfuzz_py/__init__.py, ossfuzz_py/build/build_config.py, ossfuzz_py/build/builder.py, ossfuzz_py/build/cloud_build_manager.py, ossfuzz_py/build/docker_manager.py, ossfuzz_py/core/benchmark_manager.py, ossfuzz_py/core/data_models.py, ossfuzz_py/data/__init__.py, ossfuzz_py/data/storage_adapter.py, ossfuzz_py/data/storage_manager.py, ossfuzz_py/errors/__init__.py, ossfuzz_py/errors/core.py, ossfuzz_py/errors/factory.py, ossfuzz_py/execution/__init__.py, ossfuzz_py/execution/fuzz_runner.py, ossfuzz_py/execution/fuzz_target.py, ossfuzz_py/result/__init__.py, ossfuzz_py/result/results.py, ossfuzz_py/result/textcov.py, ossfuzz_py/unittests/test_cloud_builder_pipeline.py, ossfuzz_py/unittests/test_local_builder_pipeline.py, ossfuzz_py/utils/env_utils.py, ossfuzz_py/utils/env_vars.py, ossfuzz_py/utils/file_utils.py, ossfuzz_py/utils/work_dir_manager.py
This PR introduces a comprehensive build engine and execution framework for the OSS-Fuzz Python SDK, enabling programmatic fuzzing workflows with both local and cloud environments.
- Abstract builder interface with local/cloud implementations
- Docker and Google Cloud Build integration
- Multi-sanitizer and fuzzing engine support
- Fuzzing runners for local environments
- Abstract crash and corpus result collection
- Unified storage with file system and GCS backends
- Enhanced data models for crashes and project configuration
- Centralized environment variable management
- Add more error types and error handling logic
- Extensive test coverage for build pipelines
```
ossfuzz_py/
├── build/          # Build system infrastructure
├── execution/      # Fuzzing execution framework  
├── data/ …
```
=> OSS-Fuzz Python SDK: Build Engine Implementation

agent/base_agent.py, agent/context_analyzer.py, agent/enhancer.py, common/cloud_builder.py, experimental/build_generator/llm_agent.py, llm_toolkit/prompt_builder.py, prompts/agent/context-analyzer-description.txt, prompts/agent/context-analyzer-instruction.txt, prompts/agent/context-analyzer-priming.txt, prompts/agent/enhancer-crash-priming.txt, prompts/template_xml/context-analyzer-response.txt, results.py, run_one_experiment.py, stage/analysis_stage.py
This PR makes the following changes:
- Introduces a new agent, Context Analyzer agent for analyzing the feasibility of crashes.
- Integrates the Context Analyzer agent to the Analysis stage
=> Implement and Integrate Context Analyzer agent to OSS-Fuzz-Gen

experiment/builder_runner.py, logger.py, pipeline.py, report/export.py, report/parse_logs.py, report/parse_run_log.py, report/templates/base.html, report/templates/sample/sample.html, report/templates/sample/sample.js, report/web.py, stage/analysis_stage.py, stage/base_stage.py, stage/execution_stage.py, stage/writing_stage.py
This PR adds syntax highlighting to the stack traces and turns file paths into clickable links that point directly to the source code on GitHub using the `get_project_repository` method in [`oss_fuzz_checkout.py`](https://github.com/google/oss-fuzz-gen/blob/46693b387e7e32c38a2206692bf4440a5b86c072/experiment/oss_fuzz_checkout.py#L183).
=> Syntax highlight and hyperlink crash functions + agent sections
